/* Settings.c generated by valac 0.34.5, the Vala compiler
 * generated from Settings.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>


#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;
typedef struct _ElementaryRedshiftServicesSettingsPrivate ElementaryRedshiftServicesSettingsPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ElementaryRedshiftServicesSettings {
	GraniteServicesSettings parent_instance;
	ElementaryRedshiftServicesSettingsPrivate * priv;
};

struct _ElementaryRedshiftServicesSettingsClass {
	GraniteServicesSettingsClass parent_class;
};

struct _ElementaryRedshiftServicesSettingsPrivate {
	gboolean _active;
	gboolean _indicator;
	gchar* _schedule_mode;
	gchar* _day_time;
	gchar* _night_time;
	gint _day_temperature;
	gint _night_temperature;
	gint _temperature;
	gchar* _period;
};


static gpointer elementary_redshift_services_settings_parent_class = NULL;

GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsPrivate))
enum  {
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DUMMY_PROPERTY,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_ACTIVE,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_INDICATOR,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_SCHEDULE_MODE,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TIME,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TIME,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TEMPERATURE,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TEMPERATURE,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_TEMPERATURE,
	ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_PERIOD
};
ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_new (void);
ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_construct (GType object_type);
GDateTime* elementary_redshift_services_settings_get_day (ElementaryRedshiftServicesSettings* self);
const gchar* elementary_redshift_services_settings_get_day_time (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_day (ElementaryRedshiftServicesSettings* self, GDateTime* d);
void elementary_redshift_services_settings_set_day_time (ElementaryRedshiftServicesSettings* self, const gchar* value);
GDateTime* elementary_redshift_services_settings_get_night (ElementaryRedshiftServicesSettings* self);
const gchar* elementary_redshift_services_settings_get_night_time (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_night (ElementaryRedshiftServicesSettings* self, GDateTime* d);
void elementary_redshift_services_settings_set_night_time (ElementaryRedshiftServicesSettings* self, const gchar* value);
gchar* elementary_redshift_services_settings_get_mode_name (ElementaryRedshiftServicesSettings* self, const gchar* mode);
void elementary_redshift_services_settings_reset_all (ElementaryRedshiftServicesSettings* self);
gboolean elementary_redshift_services_settings_get_active (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_active (ElementaryRedshiftServicesSettings* self, gboolean value);
gboolean elementary_redshift_services_settings_get_indicator (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_indicator (ElementaryRedshiftServicesSettings* self, gboolean value);
const gchar* elementary_redshift_services_settings_get_schedule_mode (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_schedule_mode (ElementaryRedshiftServicesSettings* self, const gchar* value);
gint elementary_redshift_services_settings_get_day_temperature (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_day_temperature (ElementaryRedshiftServicesSettings* self, gint value);
gint elementary_redshift_services_settings_get_night_temperature (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_night_temperature (ElementaryRedshiftServicesSettings* self, gint value);
gint elementary_redshift_services_settings_get_temperature (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_temperature (ElementaryRedshiftServicesSettings* self, gint value);
const gchar* elementary_redshift_services_settings_get_period (ElementaryRedshiftServicesSettings* self);
void elementary_redshift_services_settings_set_period (ElementaryRedshiftServicesSettings* self, const gchar* value);
static void elementary_redshift_services_settings_finalize (GObject* obj);
static void _vala_elementary_redshift_services_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_elementary_redshift_services_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_construct (GType object_type) {
	ElementaryRedshiftServicesSettings * self = NULL;
#line 40 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self = (ElementaryRedshiftServicesSettings*) granite_services_settings_construct (object_type, "org.pantheon.redshift");
#line 39 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return self;
#line 127 "Settings.c"
}


ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_new (void) {
#line 39 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return elementary_redshift_services_settings_construct (ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS);
#line 134 "Settings.c"
}


GDateTime* elementary_redshift_services_settings_get_day (ElementaryRedshiftServicesSettings* self) {
	GDateTime* result = NULL;
	gchar** parts = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	GDateTime* _tmp7_ = NULL;
#line 43 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_day_time;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ":", 0);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts = _tmp2_;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts_length1 = _vala_array_length (_tmp1_);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_parts_size_ = parts_length1;
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = parts[0];
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp4_ = atoi (_tmp3_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp5_ = parts[1];
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp6_ = atoi (_tmp5_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp7_ = g_date_time_new_local (2016, 11, 15, _tmp4_, _tmp6_, (gdouble) 0);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp7_;
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 179 "Settings.c"
}


void elementary_redshift_services_settings_set_day (ElementaryRedshiftServicesSettings* self, GDateTime* d) {
	GDateTime* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GDateTime* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (d != NULL);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = d;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_date_time_get_hour (_tmp0_);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp2_ = d;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = g_date_time_get_minute (_tmp2_);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp4_ = g_strdup_printf ("%i:%i", _tmp1_, _tmp3_);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp5_ = _tmp4_;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	elementary_redshift_services_settings_set_day_time (self, _tmp5_);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (_tmp5_);
#line 210 "Settings.c"
}


GDateTime* elementary_redshift_services_settings_get_night (ElementaryRedshiftServicesSettings* self) {
	GDateTime* result = NULL;
	gchar** parts = NULL;
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint parts_length1 = 0;
	gint _parts_size_ = 0;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	GDateTime* _tmp7_ = NULL;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_night_time;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp2_ = _tmp1_ = g_strsplit (_tmp0_, ":", 0);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts = _tmp2_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts_length1 = _vala_array_length (_tmp1_);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_parts_size_ = parts_length1;
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = parts[0];
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp4_ = atoi (_tmp3_);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp5_ = parts[1];
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp6_ = atoi (_tmp5_);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp7_ = g_date_time_new_local (2016, 11, 15, _tmp4_, _tmp6_, (gdouble) 0);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp7_;
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 255 "Settings.c"
}


void elementary_redshift_services_settings_set_night (ElementaryRedshiftServicesSettings* self, GDateTime* d) {
	GDateTime* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GDateTime* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 57 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (d != NULL);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = d;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_date_time_get_hour (_tmp0_);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp2_ = d;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = g_date_time_get_minute (_tmp2_);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp4_ = g_strdup_printf ("%i:%i", _tmp1_, _tmp3_);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp5_ = _tmp4_;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	elementary_redshift_services_settings_set_night_time (self, _tmp5_);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (_tmp5_);
#line 286 "Settings.c"
}


gchar* elementary_redshift_services_settings_get_mode_name (ElementaryRedshiftServicesSettings* self, const gchar* mode) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	static GQuark _tmp2_label0 = 0;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	static GQuark _tmp2_label1 = 0;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	static GQuark _tmp2_label2 = 0;
#line 61 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 61 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (mode != NULL, NULL);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = mode;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = _tmp0_;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("none")))) {
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		switch (0) {
#line 315 "Settings.c"
			default:
			{
				const gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp4_ = _ ("None");
#line 64 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp5_ = g_strdup (_tmp4_);
#line 64 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				result = _tmp5_;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				return result;
#line 328 "Settings.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("auto")))) {
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		switch (0) {
#line 334 "Settings.c"
			default:
			{
				const gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
#line 66 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp6_ = _ ("Auto");
#line 66 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp7_ = g_strdup (_tmp6_);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				result = _tmp7_;
#line 66 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				return result;
#line 347 "Settings.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("custom")))) {
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		switch (0) {
#line 353 "Settings.c"
			default:
			{
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
#line 68 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp8_ = _ ("Custom");
#line 68 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp9_ = g_strdup (_tmp8_);
#line 68 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				result = _tmp9_;
#line 68 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				return result;
#line 366 "Settings.c"
			}
		}
	} else {
#line 62 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		switch (0) {
#line 372 "Settings.c"
			default:
			{
				const gchar* _tmp10_ = NULL;
				gchar* _tmp11_ = NULL;
#line 70 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp10_ = _ ("None");
#line 70 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				_tmp11_ = g_strdup (_tmp10_);
#line 70 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				result = _tmp11_;
#line 70 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
				return result;
#line 385 "Settings.c"
			}
		}
	}
}


void elementary_redshift_services_settings_reset_all (ElementaryRedshiftServicesSettings* self) {
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	GSettings* _tmp2_ = NULL;
	GSettings* _tmp3_ = NULL;
	GSettings* _tmp4_ = NULL;
	GSettings* _tmp5_ = NULL;
	GSettings* _tmp6_ = NULL;
	GSettings* _tmp7_ = NULL;
	GSettings* _tmp8_ = NULL;
	GSettings* _tmp9_ = NULL;
	GSettings* _tmp10_ = NULL;
	GSettings* _tmp11_ = NULL;
	GSettings* _tmp12_ = NULL;
	GSettings* _tmp13_ = NULL;
#line 74 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 75 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 75 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = _tmp0_;
#line 75 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp1_, "schedule-mode");
#line 76 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp2_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp3_ = _tmp2_;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp3_, "day-time");
#line 77 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp4_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 77 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp5_ = _tmp4_;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp5_, "night-time");
#line 78 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp6_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp7_ = _tmp6_;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp7_, "day-temperature");
#line 79 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp8_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 79 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp9_ = _tmp8_;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp9_, "night-temperature");
#line 80 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp10_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp11_ = _tmp10_;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp11_, "temperature");
#line 81 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp12_ = granite_services_settings_get_schema ((GraniteServicesSettings*) self);
#line 81 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp13_ = _tmp12_;
#line 81 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_settings_reset (_tmp13_, "period");
#line 451 "Settings.c"
}


gboolean elementary_redshift_services_settings_get_active (ElementaryRedshiftServicesSettings* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_active;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 466 "Settings.c"
}


void elementary_redshift_services_settings_set_active (ElementaryRedshiftServicesSettings* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_active = _tmp0_;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "active");
#line 480 "Settings.c"
}


gboolean elementary_redshift_services_settings_get_indicator (ElementaryRedshiftServicesSettings* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_indicator;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 495 "Settings.c"
}


void elementary_redshift_services_settings_set_indicator (ElementaryRedshiftServicesSettings* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_indicator = _tmp0_;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "indicator");
#line 509 "Settings.c"
}


const gchar* elementary_redshift_services_settings_get_schedule_mode (ElementaryRedshiftServicesSettings* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_schedule_mode;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 524 "Settings.c"
}


void elementary_redshift_services_settings_set_schedule_mode (ElementaryRedshiftServicesSettings* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_schedule_mode);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_schedule_mode = _tmp1_;
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "schedule-mode");
#line 543 "Settings.c"
}


const gchar* elementary_redshift_services_settings_get_day_time (ElementaryRedshiftServicesSettings* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_day_time;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 558 "Settings.c"
}


void elementary_redshift_services_settings_set_day_time (ElementaryRedshiftServicesSettings* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_day_time);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_day_time = _tmp1_;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "day-time");
#line 577 "Settings.c"
}


const gchar* elementary_redshift_services_settings_get_night_time (ElementaryRedshiftServicesSettings* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_night_time;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 592 "Settings.c"
}


void elementary_redshift_services_settings_set_night_time (ElementaryRedshiftServicesSettings* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_night_time);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_night_time = _tmp1_;
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "night-time");
#line 611 "Settings.c"
}


gint elementary_redshift_services_settings_get_day_temperature (ElementaryRedshiftServicesSettings* self) {
	gint result;
	gint _tmp0_ = 0;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_day_temperature;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 626 "Settings.c"
}


void elementary_redshift_services_settings_set_day_temperature (ElementaryRedshiftServicesSettings* self, gint value) {
	gint _tmp0_ = 0;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_day_temperature = _tmp0_;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "day-temperature");
#line 640 "Settings.c"
}


gint elementary_redshift_services_settings_get_night_temperature (ElementaryRedshiftServicesSettings* self) {
	gint result;
	gint _tmp0_ = 0;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_night_temperature;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 655 "Settings.c"
}


void elementary_redshift_services_settings_set_night_temperature (ElementaryRedshiftServicesSettings* self, gint value) {
	gint _tmp0_ = 0;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_night_temperature = _tmp0_;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "night-temperature");
#line 669 "Settings.c"
}


gint elementary_redshift_services_settings_get_temperature (ElementaryRedshiftServicesSettings* self) {
	gint result;
	gint _tmp0_ = 0;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_temperature;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 684 "Settings.c"
}


void elementary_redshift_services_settings_set_temperature (ElementaryRedshiftServicesSettings* self, gint value) {
	gint _tmp0_ = 0;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_temperature = _tmp0_;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "temperature");
#line 698 "Settings.c"
}


const gchar* elementary_redshift_services_settings_get_period (ElementaryRedshiftServicesSettings* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = self->priv->_period;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	result = _tmp0_;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	return result;
#line 713 "Settings.c"
}


void elementary_redshift_services_settings_set_period (ElementaryRedshiftServicesSettings* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_return_if_fail (self != NULL);
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp0_ = value;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_period);
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv->_period = _tmp1_;
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_notify ((GObject *) self, "period");
#line 732 "Settings.c"
}


static void elementary_redshift_services_settings_class_init (ElementaryRedshiftServicesSettingsClass * klass) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	elementary_redshift_services_settings_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftServicesSettingsPrivate));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_elementary_redshift_services_settings_get_property;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_elementary_redshift_services_settings_set_property;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_services_settings_finalize;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_ACTIVE, g_param_spec_boolean ("active", "active", "active", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_INDICATOR, g_param_spec_boolean ("indicator", "indicator", "indicator", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_SCHEDULE_MODE, g_param_spec_string ("schedule-mode", "schedule-mode", "schedule-mode", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TIME, g_param_spec_string ("day-time", "day-time", "day-time", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TIME, g_param_spec_string ("night-time", "night-time", "night-time", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TEMPERATURE, g_param_spec_int ("day-temperature", "day-temperature", "day-temperature", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TEMPERATURE, g_param_spec_int ("night-temperature", "night-temperature", "night-temperature", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_TEMPERATURE, g_param_spec_int ("temperature", "temperature", "temperature", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_PERIOD, g_param_spec_string ("period", "period", "period", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 765 "Settings.c"
}


static void elementary_redshift_services_settings_instance_init (ElementaryRedshiftServicesSettings * self) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self->priv = ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_PRIVATE (self);
#line 772 "Settings.c"
}


static void elementary_redshift_services_settings_finalize (GObject* obj) {
	ElementaryRedshiftServicesSettings * self;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_schedule_mode);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_day_time);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_night_time);
#line 37 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	_g_free0 (self->priv->_period);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	G_OBJECT_CLASS (elementary_redshift_services_settings_parent_class)->finalize (obj);
#line 790 "Settings.c"
}


GType elementary_redshift_services_settings_get_type (void) {
	static volatile gsize elementary_redshift_services_settings_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_services_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftServicesSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_services_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftServicesSettings), 0, (GInstanceInitFunc) elementary_redshift_services_settings_instance_init, NULL };
		GType elementary_redshift_services_settings_type_id;
		elementary_redshift_services_settings_type_id = g_type_register_static (GRANITE_SERVICES_TYPE_SETTINGS, "ElementaryRedshiftServicesSettings", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_services_settings_type_id__volatile, elementary_redshift_services_settings_type_id);
	}
	return elementary_redshift_services_settings_type_id__volatile;
}


static void _vala_elementary_redshift_services_settings_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ElementaryRedshiftServicesSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	switch (property_id) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_ACTIVE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_boolean (value, elementary_redshift_services_settings_get_active (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_INDICATOR:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_boolean (value, elementary_redshift_services_settings_get_indicator (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_SCHEDULE_MODE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_string (value, elementary_redshift_services_settings_get_schedule_mode (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TIME:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_string (value, elementary_redshift_services_settings_get_day_time (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TIME:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_string (value, elementary_redshift_services_settings_get_night_time (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_int (value, elementary_redshift_services_settings_get_day_temperature (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_int (value, elementary_redshift_services_settings_get_night_temperature (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_int (value, elementary_redshift_services_settings_get_temperature (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_PERIOD:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		g_value_set_string (value, elementary_redshift_services_settings_get_period (self));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 865 "Settings.c"
		default:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 871 "Settings.c"
	}
}


static void _vala_elementary_redshift_services_settings_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ElementaryRedshiftServicesSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
	switch (property_id) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_ACTIVE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_active (self, g_value_get_boolean (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_INDICATOR:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_indicator (self, g_value_get_boolean (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_SCHEDULE_MODE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_schedule_mode (self, g_value_get_string (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TIME:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_day_time (self, g_value_get_string (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TIME:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_night_time (self, g_value_get_string (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_DAY_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_day_temperature (self, g_value_get_int (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_NIGHT_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_night_temperature (self, g_value_get_int (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_TEMPERATURE:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_temperature (self, g_value_get_int (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		case ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_PERIOD:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		elementary_redshift_services_settings_set_period (self, g_value_get_string (value));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 935 "Settings.c"
		default:
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Services/Settings.vala"
		break;
#line 941 "Settings.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



