/* config.c generated by valac 0.34.5, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define BUILD_PLUGCODENAME "elementary-redshift"
#define BUILD_PLUG_DATADIR "/usr/lib/x86_64-linux-gnu/switchboard"
#define BUILD_PLUG_PKGDATADIR "/usr/lib/x86_64-linux-gnu/switchboard/personal/elementary-redshift"
#define BUILD_WING_DATADIR "@WING_DATADIR"
#define BUILD_WING_PKGDATADIR "@WING_PKGDATADIR"
#define BUILD_INDICATOR_NAME "elementary-redshift"
#define BUILD_INDICATOR_TITLE "@INDICATORTITLE"
#define BUILD_INDICATOR_DESCRIPTION "@INDICATORDESCRIPTION"
#define BUILD_GETTEXT_PACKAGE "elementary-redshift"



