/* Plug.c generated by valac 0.34.5, the Vala compiler
 * generated from Plug.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <switchboard.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>
#include <granite.h>
#include <glib/gi18n-lib.h>
#include <gmodule.h>


#define ELEMENTARY_REDSHIFT_TYPE_PLUG (elementary_redshift_plug_get_type ())
#define ELEMENTARY_REDSHIFT_PLUG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_TYPE_PLUG, ElementaryRedshiftPlug))
#define ELEMENTARY_REDSHIFT_PLUG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_TYPE_PLUG, ElementaryRedshiftPlugClass))
#define ELEMENTARY_REDSHIFT_IS_PLUG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_TYPE_PLUG))
#define ELEMENTARY_REDSHIFT_IS_PLUG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_TYPE_PLUG))
#define ELEMENTARY_REDSHIFT_PLUG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_TYPE_PLUG, ElementaryRedshiftPlugClass))

typedef struct _ElementaryRedshiftPlug ElementaryRedshiftPlug;
typedef struct _ElementaryRedshiftPlugClass ElementaryRedshiftPlugClass;
typedef struct _ElementaryRedshiftPlugPrivate ElementaryRedshiftPlugPrivate;

#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ElementaryRedshiftPlugSearchData ElementaryRedshiftPlugSearchData;

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL (elementary_redshift_widgets_general_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneral))
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneralClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_GENERAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_GENERAL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL))
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneralClass))

typedef struct _ElementaryRedshiftWidgetsGeneral ElementaryRedshiftWidgetsGeneral;
typedef struct _ElementaryRedshiftWidgetsGeneralClass ElementaryRedshiftWidgetsGeneralClass;

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE (elementary_redshift_widgets_schedule_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsSchedule))
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsScheduleClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SCHEDULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SCHEDULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE))
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsScheduleClass))

typedef struct _ElementaryRedshiftWidgetsSchedule ElementaryRedshiftWidgetsSchedule;
typedef struct _ElementaryRedshiftWidgetsScheduleClass ElementaryRedshiftWidgetsScheduleClass;

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE (elementary_redshift_widgets_temperature_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperature))
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperatureClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_TEMPERATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_TEMPERATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE))
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperatureClass))

typedef struct _ElementaryRedshiftWidgetsTemperature ElementaryRedshiftWidgetsTemperature;
typedef struct _ElementaryRedshiftWidgetsTemperatureClass ElementaryRedshiftWidgetsTemperatureClass;

struct _ElementaryRedshiftPlug {
	SwitchboardPlug parent_instance;
	ElementaryRedshiftPlugPrivate * priv;
};

struct _ElementaryRedshiftPlugClass {
	SwitchboardPlugClass parent_class;
};

struct _ElementaryRedshiftPlugPrivate {
	GtkLinkButton* reset_button;
	GtkBox* main_box;
};

struct _ElementaryRedshiftPlugSearchData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	ElementaryRedshiftPlug* self;
	gchar* search;
	GeeTreeMap* result;
	GeeTreeMap* _tmp0_;
};


extern ElementaryRedshiftPlug* elementary_redshift_plug;
ElementaryRedshiftPlug* elementary_redshift_plug = NULL;
static gpointer elementary_redshift_plug_parent_class = NULL;
extern ElementaryRedshiftServicesSettings* elementary_redshift_plug_settings;
ElementaryRedshiftServicesSettings* elementary_redshift_plug_settings = NULL;
extern GtkSizeGroup* elementary_redshift_plug_end_size_group;
GtkSizeGroup* elementary_redshift_plug_end_size_group = NULL;
extern GtkSizeGroup* elementary_redshift_plug_start_size_group;
GtkSizeGroup* elementary_redshift_plug_start_size_group = NULL;

GType elementary_redshift_plug_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_PLUG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_TYPE_PLUG, ElementaryRedshiftPlugPrivate))
enum  {
	ELEMENTARY_REDSHIFT_PLUG_DUMMY_PROPERTY
};
GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
ElementaryRedshiftPlug* elementary_redshift_plug_new (void);
ElementaryRedshiftPlug* elementary_redshift_plug_construct (GType object_type);
#define BUILD_PLUGCODENAME "elementary-redshift"
ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_new (void);
ElementaryRedshiftServicesSettings* elementary_redshift_services_settings_construct (GType object_type);
static GtkWidget* elementary_redshift_plug_real_get_widget (SwitchboardPlug* base);
static void elementary_redshift_plug_build_ui (ElementaryRedshiftPlug* self);
static void elementary_redshift_plug_real_shown (SwitchboardPlug* base);
static void elementary_redshift_plug_real_hidden (SwitchboardPlug* base);
static void elementary_redshift_plug_real_search_callback (SwitchboardPlug* base, const gchar* location);
static void elementary_redshift_plug_real_search_data_free (gpointer _data);
static void elementary_redshift_plug_real_search (SwitchboardPlug* base, const gchar* search, GAsyncReadyCallback _callback_, gpointer _user_data_);
static gboolean elementary_redshift_plug_real_search_co (ElementaryRedshiftPlugSearchData* _data_);
ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_new (void);
ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_construct (GType object_type);
GType elementary_redshift_widgets_general_get_type (void) G_GNUC_CONST;
ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_new (void);
ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_construct (GType object_type);
GType elementary_redshift_widgets_schedule_get_type (void) G_GNUC_CONST;
ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_new (void);
ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_construct (GType object_type);
GType elementary_redshift_widgets_temperature_get_type (void) G_GNUC_CONST;
static gboolean __lambda14_ (ElementaryRedshiftPlug* self);
void elementary_redshift_services_settings_reset_all (ElementaryRedshiftServicesSettings* self);
static gboolean ___lambda14__gtk_link_button_activate_link (GtkLinkButton* _sender, gpointer self);
static void elementary_redshift_plug_finalize (GObject* obj);
SwitchboardPlug* get_plug (GModule* module);


static gpointer _g_object_ref0 (gpointer self) {
#line 42 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return self ? g_object_ref (self) : NULL;
#line 167 "Plug.c"
}


ElementaryRedshiftPlug* elementary_redshift_plug_construct (GType object_type) {
	ElementaryRedshiftPlug * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GeeTreeMap* _tmp2_ = NULL;
	GeeTreeMap* _tmp3_ = NULL;
	GeeTreeMap* _tmp4_ = NULL;
	GeeTreeMap* _tmp5_ = NULL;
	ElementaryRedshiftPlug* _tmp6_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp7_ = NULL;
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = _ ("Redshift");
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp1_ = _ ("Adjusts the color temperature of your screen according to your surroun" \
"dings");
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp2_ = gee_tree_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL);
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp3_ = _tmp2_;
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) g_object_new (object_type, "category", SWITCHBOARD_PLUG_CATEGORY_PERSONAL, "code-name", BUILD_PLUGCODENAME, "display-name", _tmp0_, "description", _tmp1_, "icon", "redshift", "supported-settings", _tmp3_, NULL);
#line 35 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_tmp3_);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp4_ = switchboard_plug_get_supported_settings ((SwitchboardPlug*) self);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp5_ = _tmp4_;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp5_, "redshift", NULL);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp6_ = _g_object_ref0 (self);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (elementary_redshift_plug);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug = _tmp6_;
#line 43 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp7_ = elementary_redshift_services_settings_new ();
#line 43 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (elementary_redshift_plug_settings);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug_settings = _tmp7_;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return self;
#line 213 "Plug.c"
}


ElementaryRedshiftPlug* elementary_redshift_plug_new (void) {
#line 34 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return elementary_redshift_plug_construct (ELEMENTARY_REDSHIFT_TYPE_PLUG);
#line 220 "Plug.c"
}


static GtkWidget* elementary_redshift_plug_real_get_widget (SwitchboardPlug* base) {
	ElementaryRedshiftPlug * self;
	GtkWidget* result = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
#line 51 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) base;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = self->priv->main_box;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	if (_tmp0_ == NULL) {
#line 53 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		elementary_redshift_plug_build_ui (self);
#line 238 "Plug.c"
	}
#line 56 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp1_ = self->priv->main_box;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp2_ = _g_object_ref0 ((GtkWidget*) _tmp1_);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	result = _tmp2_;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return result;
#line 248 "Plug.c"
}


static void elementary_redshift_plug_real_shown (SwitchboardPlug* base) {
	ElementaryRedshiftPlug * self;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) base;
#line 256 "Plug.c"
}


static void elementary_redshift_plug_real_hidden (SwitchboardPlug* base) {
	ElementaryRedshiftPlug * self;
#line 63 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) base;
#line 264 "Plug.c"
}


static void elementary_redshift_plug_real_search_callback (SwitchboardPlug* base, const gchar* location) {
	ElementaryRedshiftPlug * self;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) base;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_return_if_fail (location != NULL);
#line 274 "Plug.c"
}


static void elementary_redshift_plug_real_search_data_free (gpointer _data) {
	ElementaryRedshiftPlugSearchData* _data_;
	_data_ = _data;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_free0 (_data_->search);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_data_->result);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_data_->self);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_slice_free (ElementaryRedshiftPlugSearchData, _data_);
#line 289 "Plug.c"
}


static void elementary_redshift_plug_real_search (SwitchboardPlug* base, const gchar* search, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	ElementaryRedshiftPlug * self;
	ElementaryRedshiftPlugSearchData* _data_;
	ElementaryRedshiftPlug* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = (ElementaryRedshiftPlug*) base;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_ = g_slice_new0 (ElementaryRedshiftPlugSearchData);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, elementary_redshift_plug_real_search);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, elementary_redshift_plug_real_search_data_free);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->self = _tmp0_;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp1_ = search;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_free0 (_data_->search);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->search = _tmp2_;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug_real_search_co (_data_);
#line 321 "Plug.c"
}


static GeeTreeMap* elementary_redshift_plug_real_search_finish (SwitchboardPlug* base, GAsyncResult* _res_) {
	GeeTreeMap* result;
	ElementaryRedshiftPlugSearchData* _data_;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	result = _data_->result;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->result = NULL;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return result;
#line 336 "Plug.c"
}


static gboolean elementary_redshift_plug_real_search_co (ElementaryRedshiftPlugSearchData* _data_) {
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	switch (_data_->_state_) {
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		case 0:
#line 345 "Plug.c"
		goto _state_0;
		default:
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		g_assert_not_reached ();
#line 350 "Plug.c"
	}
	_state_0:
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->_tmp0_ = NULL;
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->_tmp0_ = gee_tree_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_data_->result = _data_->_tmp0_;
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	if (_data_->_state_ == 0) {
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 363 "Plug.c"
	} else {
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 367 "Plug.c"
	}
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_unref (_data_->_async_result);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return FALSE;
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	if (_data_->_state_ == 0) {
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 377 "Plug.c"
	} else {
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 381 "Plug.c"
	}
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_unref (_data_->_async_result);
#line 72 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return FALSE;
#line 387 "Plug.c"
}


static gboolean __lambda14_ (ElementaryRedshiftPlug* self) {
	gboolean result = FALSE;
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
#line 94 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 94 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_services_settings_reset_all (_tmp0_);
#line 95 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	result = TRUE;
#line 95 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return result;
#line 402 "Plug.c"
}


static gboolean ___lambda14__gtk_link_button_activate_link (GtkLinkButton* _sender, gpointer self) {
	gboolean result;
	result = __lambda14_ ((ElementaryRedshiftPlug*) self);
#line 93 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return result;
#line 411 "Plug.c"
}


static void elementary_redshift_plug_build_ui (ElementaryRedshiftPlug* self) {
	GtkBox* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLinkButton* _tmp2_ = NULL;
	GtkLinkButton* _tmp3_ = NULL;
	GtkLinkButton* _tmp4_ = NULL;
	GtkLinkButton* _tmp5_ = NULL;
	GtkLinkButton* _tmp6_ = NULL;
	GtkBox* _tmp7_ = NULL;
	ElementaryRedshiftWidgetsGeneral* _tmp8_ = NULL;
	ElementaryRedshiftWidgetsGeneral* _tmp9_ = NULL;
	GtkBox* _tmp10_ = NULL;
	ElementaryRedshiftWidgetsSchedule* _tmp11_ = NULL;
	ElementaryRedshiftWidgetsSchedule* _tmp12_ = NULL;
	GtkBox* _tmp13_ = NULL;
	ElementaryRedshiftWidgetsTemperature* _tmp14_ = NULL;
	ElementaryRedshiftWidgetsTemperature* _tmp15_ = NULL;
	GtkBox* _tmp16_ = NULL;
	GtkLinkButton* _tmp17_ = NULL;
	GtkBox* _tmp18_ = NULL;
	GtkLinkButton* _tmp19_ = NULL;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_ref_sink (_tmp0_);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (self->priv->main_box);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self->priv->main_box = _tmp0_;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp1_ = _ ("Reset to Default");
#line 80 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp2_ = (GtkLinkButton*) gtk_link_button_new (_tmp1_);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_ref_sink (_tmp2_);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (self->priv->reset_button);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self->priv->reset_button = _tmp2_;
#line 81 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp3_ = self->priv->reset_button;
#line 81 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_set ((GtkWidget*) _tmp3_, "margin", 12, NULL);
#line 82 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp4_ = self->priv->reset_button;
#line 82 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp4_, TRUE);
#line 83 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp5_ = self->priv->reset_button;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp5_, GTK_ALIGN_END);
#line 84 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp6_ = self->priv->reset_button;
#line 84 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp6_, GTK_ALIGN_END);
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp7_ = self->priv->main_box;
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp8_ = elementary_redshift_widgets_general_new ();
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_ref_sink (_tmp8_);
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp9_ = _tmp8_;
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_container_add ((GtkContainer*) _tmp7_, (GtkWidget*) _tmp9_);
#line 86 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_tmp9_);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp10_ = self->priv->main_box;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp11_ = elementary_redshift_widgets_schedule_new ();
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_ref_sink (_tmp11_);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp12_ = _tmp11_;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_container_add ((GtkContainer*) _tmp10_, (GtkWidget*) _tmp12_);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_tmp12_);
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp13_ = self->priv->main_box;
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp14_ = elementary_redshift_widgets_temperature_new ();
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_object_ref_sink (_tmp14_);
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp15_ = _tmp14_;
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_container_add ((GtkContainer*) _tmp13_, (GtkWidget*) _tmp15_);
#line 88 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (_tmp15_);
#line 89 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp16_ = self->priv->main_box;
#line 89 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp17_ = self->priv->reset_button;
#line 89 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_container_add ((GtkContainer*) _tmp16_, (GtkWidget*) _tmp17_);
#line 91 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp18_ = self->priv->main_box;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp18_);
#line 93 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp19_ = self->priv->reset_button;
#line 93 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_signal_connect_object (_tmp19_, "activate-link", (GCallback) ___lambda14__gtk_link_button_activate_link, self, 0);
#line 522 "Plug.c"
}


static void elementary_redshift_plug_class_init (ElementaryRedshiftPlugClass * klass) {
	GtkSizeGroup* _tmp0_ = NULL;
	GtkSizeGroup* _tmp1_ = NULL;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug_parent_class = g_type_class_peek_parent (klass);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftPlugPrivate));
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->get_widget = (GtkWidget* (*)(SwitchboardPlug*)) elementary_redshift_plug_real_get_widget;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->shown = (void (*)(SwitchboardPlug*)) elementary_redshift_plug_real_shown;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->hidden = (void (*)(SwitchboardPlug*)) elementary_redshift_plug_real_hidden;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->search_callback = (void (*)(SwitchboardPlug*, const gchar*)) elementary_redshift_plug_real_search_callback;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->search = (void (*)(SwitchboardPlug*, const gchar*, GAsyncReadyCallback, gpointer)) elementary_redshift_plug_real_search;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	((SwitchboardPlugClass *) klass)->search_finish = (GeeTreeMap* (*)(SwitchboardPlug*, GAsyncResult*)) elementary_redshift_plug_real_search_finish;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_plug_finalize;
#line 47 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = gtk_size_group_new (GTK_SIZE_GROUP_HORIZONTAL);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (elementary_redshift_plug_end_size_group);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug_end_size_group = _tmp0_;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp1_ = gtk_size_group_new (GTK_SIZE_GROUP_HORIZONTAL);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (elementary_redshift_plug_start_size_group);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	elementary_redshift_plug_start_size_group = _tmp1_;
#line 559 "Plug.c"
}


static void elementary_redshift_plug_instance_init (ElementaryRedshiftPlug * self) {
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self->priv = ELEMENTARY_REDSHIFT_PLUG_GET_PRIVATE (self);
#line 566 "Plug.c"
}


static void elementary_redshift_plug_finalize (GObject* obj) {
	ElementaryRedshiftPlug * self;
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_TYPE_PLUG, ElementaryRedshiftPlug);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (self->priv->reset_button);
#line 32 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_g_object_unref0 (self->priv->main_box);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	G_OBJECT_CLASS (elementary_redshift_plug_parent_class)->finalize (obj);
#line 580 "Plug.c"
}


GType elementary_redshift_plug_get_type (void) {
	static volatile gsize elementary_redshift_plug_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_plug_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftPlugClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_plug_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftPlug), 0, (GInstanceInitFunc) elementary_redshift_plug_instance_init, NULL };
		GType elementary_redshift_plug_type_id;
		elementary_redshift_plug_type_id = g_type_register_static (SWITCHBOARD_TYPE_PLUG, "ElementaryRedshiftPlug", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_plug_type_id__volatile, elementary_redshift_plug_type_id);
	}
	return elementary_redshift_plug_type_id__volatile;
}


SwitchboardPlug* get_plug (GModule* module) {
	SwitchboardPlug* result = NULL;
	ElementaryRedshiftPlug* plug = NULL;
	ElementaryRedshiftPlug* _tmp0_ = NULL;
#line 101 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_return_val_if_fail (module != NULL, NULL);
#line 102 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	g_debug ("Plug.vala:102: Activating Elementary Redshift plug");
#line 103 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	_tmp0_ = elementary_redshift_plug_new ();
#line 103 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	plug = _tmp0_;
#line 104 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	result = (SwitchboardPlug*) plug;
#line 104 "/home/samthomas/Development/elementary-redshift/src/Plug.vala"
	return result;
#line 612 "Plug.c"
}



