/* RedshiftDaemon.c generated by valac 0.34.5, the Vala compiler
 * generated from RedshiftDaemon.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER (elementary_redshift_daemon_controller_get_type ())
#define ELEMENTARY_REDSHIFT_DAEMON_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER, ElementaryRedshiftDaemonController))
#define ELEMENTARY_REDSHIFT_DAEMON_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER, ElementaryRedshiftDaemonControllerClass))
#define ELEMENTARY_REDSHIFT_DAEMON_IS_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER))
#define ELEMENTARY_REDSHIFT_DAEMON_IS_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER))
#define ELEMENTARY_REDSHIFT_DAEMON_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER, ElementaryRedshiftDaemonControllerClass))

typedef struct _ElementaryRedshiftDaemonController ElementaryRedshiftDaemonController;
typedef struct _ElementaryRedshiftDaemonControllerClass ElementaryRedshiftDaemonControllerClass;
typedef struct _ElementaryRedshiftDaemonControllerPrivate ElementaryRedshiftDaemonControllerPrivate;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ElementaryRedshiftDaemonController {
	GApplication parent_instance;
	ElementaryRedshiftDaemonControllerPrivate * priv;
};

struct _ElementaryRedshiftDaemonControllerClass {
	GApplicationClass parent_class;
};


static gpointer elementary_redshift_daemon_controller_parent_class = NULL;

GType elementary_redshift_daemon_controller_get_type (void) G_GNUC_CONST;
enum  {
	ELEMENTARY_REDSHIFT_DAEMON_CONTROLLER_DUMMY_PROPERTY
};
ElementaryRedshiftDaemonController* elementary_redshift_daemon_controller_new (void);
ElementaryRedshiftDaemonController* elementary_redshift_daemon_controller_construct (GType object_type);
static void elementary_redshift_daemon_controller_real_startup (GApplication* base);
static void elementary_redshift_daemon_controller_real_activate (GApplication* base);
static gboolean elementary_redshift_daemon_controller_real_dbus_register (GApplication* base, GDBusConnection* connection, const gchar* object_path, GError** error);
static void elementary_redshift_daemon_controller_finalize (GObject* obj);
gint elementary_redshift_daemon_main (gchar** args, int args_length1);


ElementaryRedshiftDaemonController* elementary_redshift_daemon_controller_construct (GType object_type) {
	ElementaryRedshiftDaemonController * self = NULL;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	self = (ElementaryRedshiftDaemonController*) g_object_new (object_type, "application-id", "org.pantheon.redshift", "flags", G_APPLICATION_NON_UNIQUE, NULL);
#line 27 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_application_set_inactivity_timeout ((GApplication*) self, (guint) 1000);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	return self;
#line 79 "RedshiftDaemon.c"
}


ElementaryRedshiftDaemonController* elementary_redshift_daemon_controller_new (void) {
#line 25 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	return elementary_redshift_daemon_controller_construct (ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER);
#line 86 "RedshiftDaemon.c"
}


static void elementary_redshift_daemon_controller_real_startup (GApplication* base) {
	ElementaryRedshiftDaemonController * self;
#line 34 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	self = (ElementaryRedshiftDaemonController*) base;
#line 35 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_message ("RedshiftDaemon.vala:35: Redshift Daemon Started");
#line 36 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	G_APPLICATION_CLASS (elementary_redshift_daemon_controller_parent_class)->startup (G_TYPE_CHECK_INSTANCE_CAST (self, g_application_get_type (), GApplication));
#line 38 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_application_hold ((GApplication*) self);
#line 100 "RedshiftDaemon.c"
}


static void elementary_redshift_daemon_controller_real_activate (GApplication* base) {
	ElementaryRedshiftDaemonController * self;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	self = (ElementaryRedshiftDaemonController*) base;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_message ("RedshiftDaemon.vala:42: Daemon Activated");
#line 110 "RedshiftDaemon.c"
}


static gboolean elementary_redshift_daemon_controller_real_dbus_register (GApplication* base, GDBusConnection* connection, const gchar* object_path, GError** error) {
	ElementaryRedshiftDaemonController * self;
	gboolean result = FALSE;
#line 45 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	self = (ElementaryRedshiftDaemonController*) base;
#line 45 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_return_val_if_fail (connection != NULL, FALSE);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_return_val_if_fail (object_path != NULL, FALSE);
#line 46 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	result = FALSE;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	return result;
#line 127 "RedshiftDaemon.c"
}


static void elementary_redshift_daemon_controller_class_init (ElementaryRedshiftDaemonControllerClass * klass) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	elementary_redshift_daemon_controller_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	((GApplicationClass *) klass)->startup = (void (*)(GApplication*)) elementary_redshift_daemon_controller_real_startup;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) elementary_redshift_daemon_controller_real_activate;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	((GApplicationClass *) klass)->dbus_register = (gboolean (*)(GApplication*, GDBusConnection*, const gchar*, GError**)) elementary_redshift_daemon_controller_real_dbus_register;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_daemon_controller_finalize;
#line 142 "RedshiftDaemon.c"
}


static void elementary_redshift_daemon_controller_instance_init (ElementaryRedshiftDaemonController * self) {
}


static void elementary_redshift_daemon_controller_finalize (GObject* obj) {
	ElementaryRedshiftDaemonController * self;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_DAEMON_TYPE_CONTROLLER, ElementaryRedshiftDaemonController);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	g_application_release ((GApplication*) self);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	G_OBJECT_CLASS (elementary_redshift_daemon_controller_parent_class)->finalize (obj);
#line 158 "RedshiftDaemon.c"
}


GType elementary_redshift_daemon_controller_get_type (void) {
	static volatile gsize elementary_redshift_daemon_controller_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_daemon_controller_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftDaemonControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_daemon_controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftDaemonController), 0, (GInstanceInitFunc) elementary_redshift_daemon_controller_instance_init, NULL };
		GType elementary_redshift_daemon_controller_type_id;
		elementary_redshift_daemon_controller_type_id = g_type_register_static (g_application_get_type (), "ElementaryRedshiftDaemonController", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_daemon_controller_type_id__volatile, elementary_redshift_daemon_controller_type_id);
	}
	return elementary_redshift_daemon_controller_type_id__volatile;
}


gint elementary_redshift_daemon_main (gchar** args, int args_length1) {
	gint result = 0;
	ElementaryRedshiftDaemonController* app = NULL;
	ElementaryRedshiftDaemonController* _tmp0_ = NULL;
	gchar** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gint _tmp3_ = 0;
	GError * _inner_error_ = NULL;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	_tmp0_ = elementary_redshift_daemon_controller_new ();
#line 52 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	app = _tmp0_;
#line 186 "RedshiftDaemon.c"
	{
#line 56 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		g_application_register ((GApplication*) app, NULL, &_inner_error_);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 192 "RedshiftDaemon.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		e = _inner_error_;
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		_inner_error_ = NULL;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		g_error ("RedshiftDaemon.vala:58: Unable to register redshift daemon");
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		_g_error_free0 (e);
#line 208 "RedshiftDaemon.c"
	}
	__finally0:
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 213 "RedshiftDaemon.c"
		gint _tmp1_ = 0;
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		_g_object_unref0 (app);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		g_clear_error (&_inner_error_);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
		return _tmp1_;
#line 223 "RedshiftDaemon.c"
	}
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	_tmp2_ = args;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	_tmp2__length1 = args_length1;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	_tmp3_ = g_application_run ((GApplication*) app, _tmp2__length1, _tmp2_);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	result = _tmp3_;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	_g_object_unref0 (app);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	return result;
#line 237 "RedshiftDaemon.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 51 "/home/samthomas/Development/elementary-redshift/src/Daemon/RedshiftDaemon.vala"
	return elementary_redshift_daemon_main (argv, argc);
#line 247 "RedshiftDaemon.c"
}



