/* General.c generated by valac 0.34.5, the Vala compiler
 * generated from General.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <gio/gio.h>


#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL (elementary_redshift_widgets_general_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneral))
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneralClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_GENERAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_GENERAL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL))
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneralClass))

typedef struct _ElementaryRedshiftWidgetsGeneral ElementaryRedshiftWidgetsGeneral;
typedef struct _ElementaryRedshiftWidgetsGeneralClass ElementaryRedshiftWidgetsGeneralClass;
typedef struct _ElementaryRedshiftWidgetsGeneralPrivate ElementaryRedshiftWidgetsGeneralPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL (elementary_redshift_widgets_setting_label_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))

typedef struct _ElementaryRedshiftWidgetsSettingLabel ElementaryRedshiftWidgetsSettingLabel;
typedef struct _ElementaryRedshiftWidgetsSettingLabelClass ElementaryRedshiftWidgetsSettingLabelClass;

#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;

struct _ElementaryRedshiftWidgetsGeneral {
	GtkGrid parent_instance;
	ElementaryRedshiftWidgetsGeneralPrivate * priv;
};

struct _ElementaryRedshiftWidgetsGeneralClass {
	GtkGridClass parent_class;
};

struct _ElementaryRedshiftWidgetsGeneralPrivate {
	GtkSwitch* redshift_switch;
	GtkSwitch* indicator_switch;
};


static gpointer elementary_redshift_widgets_general_parent_class = NULL;
extern GtkSizeGroup* elementary_redshift_plug_start_size_group;
extern ElementaryRedshiftServicesSettings* elementary_redshift_plug_settings;

GType elementary_redshift_widgets_general_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneralPrivate))
enum  {
	ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_DUMMY_PROPERTY
};
ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_new (void);
ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_construct (GType object_type);
static GObject * elementary_redshift_widgets_general_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label);
GType elementary_redshift_widgets_setting_label_get_type (void) G_GNUC_CONST;
GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
static void elementary_redshift_widgets_general_finalize (GObject* obj);


ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_construct (GType object_type) {
	ElementaryRedshiftWidgetsGeneral * self = NULL;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self = (ElementaryRedshiftWidgetsGeneral*) g_object_new (object_type, "margin", 12, "row-spacing", 12, "column-spacing", 12, "halign", GTK_ALIGN_CENTER, NULL);
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	return self;
#line 110 "General.c"
}


ElementaryRedshiftWidgetsGeneral* elementary_redshift_widgets_general_new (void) {
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	return elementary_redshift_widgets_general_construct (ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL);
#line 117 "General.c"
}


static GObject * elementary_redshift_widgets_general_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ElementaryRedshiftWidgetsGeneral * self;
	GtkLabel* general_label = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_ = NULL;
	GtkSizeGroup* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	GtkSwitch* _tmp8_ = NULL;
	GtkSwitch* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp12_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp13_ = NULL;
	GtkSwitch* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp16_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp17_ = NULL;
	GtkSwitch* _tmp18_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp19_ = NULL;
	GSettings* _tmp20_ = NULL;
	GSettings* _tmp21_ = NULL;
	GtkSwitch* _tmp22_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp23_ = NULL;
	GSettings* _tmp24_ = NULL;
	GSettings* _tmp25_ = NULL;
	GtkSwitch* _tmp26_ = NULL;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	parent_class = G_OBJECT_CLASS (elementary_redshift_widgets_general_parent_class);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneral);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp0_ = _ ("General");
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_object_ref_sink (_tmp1_);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	general_label = _tmp1_;
#line 39 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp2_ = general_label;
#line 39 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_label_set_xalign (_tmp2_, (gfloat) 0);
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp3_ = general_label;
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp4_ = general_label;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_style_context_add_class (_tmp5_, "h4");
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp6_ = elementary_redshift_plug_start_size_group;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp7_ = general_label;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_size_group_add_widget (_tmp6_, (GtkWidget*) _tmp7_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp8_ = (GtkSwitch*) gtk_switch_new ();
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_object_ref_sink (_tmp8_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (self->priv->redshift_switch);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self->priv->redshift_switch = _tmp8_;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp9_ = (GtkSwitch*) gtk_switch_new ();
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_object_ref_sink (_tmp9_);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (self->priv->indicator_switch);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self->priv->indicator_switch = _tmp9_;
#line 50 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp10_ = general_label;
#line 50 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp10_, 0, 0, 1, 1);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp11_ = _ ("Active:");
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp12_ = elementary_redshift_widgets_setting_label_new (_tmp11_);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_object_ref_sink (_tmp12_);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp13_ = _tmp12_;
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp13_, 0, 1, 1, 1);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (_tmp13_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp14_ = self->priv->redshift_switch;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp14_, 1, 1, 1, 1);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp15_ = _ ("Show indicator:");
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp16_ = elementary_redshift_widgets_setting_label_new (_tmp15_);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_object_ref_sink (_tmp16_);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp17_ = _tmp16_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp17_, 0, 2, 1, 1);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (_tmp17_);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp18_ = self->priv->indicator_switch;
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp18_, 1, 2, 1, 1);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp19_ = elementary_redshift_plug_settings;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp20_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp19_);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp21_ = _tmp20_;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp22_ = self->priv->redshift_switch;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_settings_bind (_tmp21_, "active", (GObject*) _tmp22_, "active", G_SETTINGS_BIND_DEFAULT);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp23_ = elementary_redshift_plug_settings;
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp24_ = granite_services_settings_get_schema ((GraniteServicesSettings*) _tmp23_);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp25_ = _tmp24_;
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_tmp26_ = self->priv->indicator_switch;
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_settings_bind (_tmp25_, "indicator", (GObject*) _tmp26_, "active", G_SETTINGS_BIND_DEFAULT);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (general_label);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	return obj;
#line 263 "General.c"
}


static void elementary_redshift_widgets_general_class_init (ElementaryRedshiftWidgetsGeneralClass * klass) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	elementary_redshift_widgets_general_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftWidgetsGeneralPrivate));
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	G_OBJECT_CLASS (klass)->constructor = elementary_redshift_widgets_general_constructor;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_widgets_general_finalize;
#line 276 "General.c"
}


static void elementary_redshift_widgets_general_instance_init (ElementaryRedshiftWidgetsGeneral * self) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self->priv = ELEMENTARY_REDSHIFT_WIDGETS_GENERAL_GET_PRIVATE (self);
#line 283 "General.c"
}


static void elementary_redshift_widgets_general_finalize (GObject* obj) {
	ElementaryRedshiftWidgetsGeneral * self;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_GENERAL, ElementaryRedshiftWidgetsGeneral);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (self->priv->redshift_switch);
#line 27 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	_g_object_unref0 (self->priv->indicator_switch);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/General.vala"
	G_OBJECT_CLASS (elementary_redshift_widgets_general_parent_class)->finalize (obj);
#line 297 "General.c"
}


GType elementary_redshift_widgets_general_get_type (void) {
	static volatile gsize elementary_redshift_widgets_general_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_widgets_general_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftWidgetsGeneralClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_widgets_general_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftWidgetsGeneral), 0, (GInstanceInitFunc) elementary_redshift_widgets_general_instance_init, NULL };
		GType elementary_redshift_widgets_general_type_id;
		elementary_redshift_widgets_general_type_id = g_type_register_static (gtk_grid_get_type (), "ElementaryRedshiftWidgetsGeneral", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_widgets_general_type_id__volatile, elementary_redshift_widgets_general_type_id);
	}
	return elementary_redshift_widgets_general_type_id__volatile;
}



