/* InformationGrid.c generated by valac 0.34.5, the Vala compiler
 * generated from InformationGrid.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>


#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID (elementary_redshift_widgets_information_grid_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGrid))
#define ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGridClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_INFORMATION_GRID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_INFORMATION_GRID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID))
#define ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGridClass))

typedef struct _ElementaryRedshiftWidgetsInformationGrid ElementaryRedshiftWidgetsInformationGrid;
typedef struct _ElementaryRedshiftWidgetsInformationGridClass ElementaryRedshiftWidgetsInformationGridClass;
typedef struct _ElementaryRedshiftWidgetsInformationGridPrivate ElementaryRedshiftWidgetsInformationGridPrivate;

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL (elementary_redshift_widgets_setting_label_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))

typedef struct _ElementaryRedshiftWidgetsSettingLabel ElementaryRedshiftWidgetsSettingLabel;
typedef struct _ElementaryRedshiftWidgetsSettingLabelClass ElementaryRedshiftWidgetsSettingLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ElementaryRedshiftWidgetsInformationGrid {
	GtkGrid parent_instance;
	ElementaryRedshiftWidgetsInformationGridPrivate * priv;
};

struct _ElementaryRedshiftWidgetsInformationGridClass {
	GtkGridClass parent_class;
};

struct _ElementaryRedshiftWidgetsInformationGridPrivate {
	ElementaryRedshiftWidgetsSettingLabel* mode_setting_label;
	ElementaryRedshiftWidgetsSettingLabel* temperature_setting_label;
	ElementaryRedshiftWidgetsSettingLabel* period_setting_label;
	GtkLabel* mode_label;
	GtkLabel* temperature_label;
	GtkLabel* period_label;
	GtkScale* temperature_scale;
};


static gpointer elementary_redshift_widgets_information_grid_parent_class = NULL;
extern ElementaryRedshiftServicesSettings* elementary_redshift_indicator_settings;

GType elementary_redshift_widgets_information_grid_get_type (void) G_GNUC_CONST;
GType elementary_redshift_widgets_setting_label_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGridPrivate))
enum  {
	ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID_DUMMY_PROPERTY
};
ElementaryRedshiftWidgetsInformationGrid* elementary_redshift_widgets_information_grid_new (void);
ElementaryRedshiftWidgetsInformationGrid* elementary_redshift_widgets_information_grid_construct (GType object_type);
static void elementary_redshift_widgets_information_grid_update (ElementaryRedshiftWidgetsInformationGrid* self);
GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
const gchar* elementary_redshift_services_settings_get_schedule_mode (ElementaryRedshiftServicesSettings* self);
gint elementary_redshift_services_settings_get_temperature (ElementaryRedshiftServicesSettings* self);
static void elementary_redshift_widgets_information_grid_connect_signals (ElementaryRedshiftWidgetsInformationGrid* self);
static void __lambda4_ (ElementaryRedshiftWidgetsInformationGrid* self);
void elementary_redshift_services_settings_set_temperature (ElementaryRedshiftServicesSettings* self, gint value);
static void ___lambda4__gtk_range_value_changed (GtkRange* _sender, gpointer self);
static GObject * elementary_redshift_widgets_information_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label);
gchar* elementary_redshift_services_settings_get_mode_name (ElementaryRedshiftServicesSettings* self, const gchar* mode);
static gchar* _elementary_redshift_widgets_information_grid___lambda5_ (ElementaryRedshiftWidgetsInformationGrid* self, gdouble val);
static gchar* __elementary_redshift_widgets_information_grid___lambda5__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self);
static void elementary_redshift_widgets_information_grid_finalize (GObject* obj);


ElementaryRedshiftWidgetsInformationGrid* elementary_redshift_widgets_information_grid_construct (GType object_type) {
	ElementaryRedshiftWidgetsInformationGrid * self = NULL;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self = (ElementaryRedshiftWidgetsInformationGrid*) g_object_new (object_type, "margin", 12, "row-spacing", 6, "column-spacing", 6, "halign", GTK_ALIGN_CENTER, NULL);
#line 35 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	return self;
#line 124 "InformationGrid.c"
}


ElementaryRedshiftWidgetsInformationGrid* elementary_redshift_widgets_information_grid_new (void) {
#line 35 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	return elementary_redshift_widgets_information_grid_construct (ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID);
#line 131 "InformationGrid.c"
}


static void elementary_redshift_widgets_information_grid_update (ElementaryRedshiftWidgetsInformationGrid* self) {
	gboolean _tmp0_ = FALSE;
	ElementaryRedshiftServicesSettings* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
#line 75 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_return_if_fail (self != NULL);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp1_ = elementary_redshift_indicator_settings;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp2_ = elementary_redshift_services_settings_get_schedule_mode (_tmp1_);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp3_ = _tmp2_;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	if (g_strcmp0 (_tmp3_, "auto") == 0) {
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp0_ = TRUE;
#line 152 "InformationGrid.c"
	} else {
		ElementaryRedshiftServicesSettings* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp4_ = elementary_redshift_indicator_settings;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp5_ = elementary_redshift_services_settings_get_schedule_mode (_tmp4_);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp6_ = _tmp5_;
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp0_ = g_strcmp0 (_tmp6_, "custom") == 0;
#line 165 "InformationGrid.c"
	}
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	if (_tmp0_) {
#line 169 "InformationGrid.c"
		ElementaryRedshiftWidgetsSettingLabel* _tmp7_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp8_ = NULL;
		GtkLabel* _tmp9_ = NULL;
		GtkLabel* _tmp10_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp11_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp12_ = NULL;
		GtkLabel* _tmp13_ = NULL;
		GtkLabel* _tmp14_ = NULL;
		GtkScale* _tmp15_ = NULL;
		GtkScale* _tmp16_ = NULL;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp7_ = self->priv->temperature_setting_label;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp7_, FALSE);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp8_ = self->priv->temperature_setting_label;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_show ((GtkWidget*) _tmp8_);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp9_ = self->priv->temperature_label;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp9_, FALSE);
#line 81 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp10_ = self->priv->temperature_label;
#line 81 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_show ((GtkWidget*) _tmp10_);
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp11_ = self->priv->period_setting_label;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp11_, FALSE);
#line 84 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp12_ = self->priv->period_setting_label;
#line 84 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_show ((GtkWidget*) _tmp12_);
#line 86 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp13_ = self->priv->period_label;
#line 86 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp13_, FALSE);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp14_ = self->priv->period_label;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_show ((GtkWidget*) _tmp14_);
#line 89 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp15_ = self->priv->temperature_scale;
#line 89 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp15_, TRUE);
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp16_ = self->priv->temperature_scale;
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_hide ((GtkWidget*) _tmp16_);
#line 220 "InformationGrid.c"
	} else {
		ElementaryRedshiftWidgetsSettingLabel* _tmp17_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp18_ = NULL;
		GtkLabel* _tmp19_ = NULL;
		GtkLabel* _tmp20_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp21_ = NULL;
		ElementaryRedshiftWidgetsSettingLabel* _tmp22_ = NULL;
		GtkLabel* _tmp23_ = NULL;
		GtkLabel* _tmp24_ = NULL;
		GtkScale* _tmp25_ = NULL;
		GtkScale* _tmp26_ = NULL;
		GtkScale* _tmp27_ = NULL;
		GtkAdjustment* _tmp28_ = NULL;
		GtkAdjustment* _tmp29_ = NULL;
		ElementaryRedshiftServicesSettings* _tmp30_ = NULL;
		gint _tmp31_ = 0;
		gint _tmp32_ = 0;
#line 92 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp17_ = self->priv->temperature_setting_label;
#line 92 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp17_, TRUE);
#line 93 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp18_ = self->priv->temperature_setting_label;
#line 93 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_hide ((GtkWidget*) _tmp18_);
#line 95 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp19_ = self->priv->temperature_label;
#line 95 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp19_, TRUE);
#line 96 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp20_ = self->priv->temperature_label;
#line 96 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_hide ((GtkWidget*) _tmp20_);
#line 98 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp21_ = self->priv->period_setting_label;
#line 98 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp21_, TRUE);
#line 99 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp22_ = self->priv->period_setting_label;
#line 99 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_hide ((GtkWidget*) _tmp22_);
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp23_ = self->priv->period_label;
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp23_, TRUE);
#line 102 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp24_ = self->priv->period_label;
#line 102 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_hide ((GtkWidget*) _tmp24_);
#line 104 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp25_ = self->priv->temperature_scale;
#line 104 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp25_, FALSE);
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp26_ = self->priv->temperature_scale;
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_widget_show ((GtkWidget*) _tmp26_);
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp27_ = self->priv->temperature_scale;
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp28_ = gtk_range_get_adjustment ((GtkRange*) _tmp27_);
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp29_ = _tmp28_;
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp30_ = elementary_redshift_indicator_settings;
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp31_ = elementary_redshift_services_settings_get_temperature (_tmp30_);
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		_tmp32_ = _tmp31_;
#line 106 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
		gtk_adjustment_set_value (_tmp29_, (gdouble) (_tmp32_ / 100));
#line 292 "InformationGrid.c"
	}
}


static void __lambda4_ (ElementaryRedshiftWidgetsInformationGrid* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GtkScale* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_ = NULL;
	GtkAdjustment* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp0_ = elementary_redshift_indicator_settings;
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp1_ = self->priv->temperature_scale;
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp2_ = gtk_range_get_adjustment ((GtkRange*) _tmp1_);
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp3_ = _tmp2_;
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp4_ = gtk_adjustment_get_value (_tmp3_);
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp5_ = _tmp4_;
#line 125 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	elementary_redshift_services_settings_set_temperature (_tmp0_, (gint) (_tmp5_ * 100));
#line 318 "InformationGrid.c"
}


static void ___lambda4__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 124 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	__lambda4_ ((ElementaryRedshiftWidgetsInformationGrid*) self);
#line 325 "InformationGrid.c"
}


static void elementary_redshift_widgets_information_grid_connect_signals (ElementaryRedshiftWidgetsInformationGrid* self) {
	GtkScale* _tmp0_ = NULL;
#line 110 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_return_if_fail (self != NULL);
#line 124 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp0_ = self->priv->temperature_scale;
#line 124 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_signal_connect_object ((GtkRange*) _tmp0_, "value-changed", (GCallback) ___lambda4__gtk_range_value_changed, self, 0);
#line 337 "InformationGrid.c"
}


static gchar* _elementary_redshift_widgets_information_grid___lambda5_ (ElementaryRedshiftWidgetsInformationGrid* self, gdouble val) {
	gchar* result = NULL;
	gdouble _tmp0_ = 0.0;
	gchar* _tmp1_ = NULL;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp0_ = val;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp1_ = g_strdup_printf (" %.f00 K", _tmp0_);
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	result = _tmp1_;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	return result;
#line 353 "InformationGrid.c"
}


static gchar* __elementary_redshift_widgets_information_grid___lambda5__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self) {
	gchar* result;
	result = _elementary_redshift_widgets_information_grid___lambda5_ ((ElementaryRedshiftWidgetsInformationGrid*) self, value);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	return result;
#line 362 "InformationGrid.c"
}


static GObject * elementary_redshift_widgets_information_grid_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ElementaryRedshiftWidgetsInformationGrid * self;
	const gchar* _tmp0_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp1_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp2_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkLabel* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	GtkLabel* _tmp18_ = NULL;
	GtkLabel* _tmp19_ = NULL;
	GtkScale* _tmp20_ = NULL;
	GtkScale* _tmp21_ = NULL;
	GtkAdjustment* _tmp22_ = NULL;
	GtkAdjustment* _tmp23_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp24_ = NULL;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	GtkScale* _tmp27_ = NULL;
	GtkScale* _tmp28_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp29_ = NULL;
	GtkLabel* _tmp30_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp31_ = NULL;
	GtkLabel* _tmp32_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp33_ = NULL;
	GtkLabel* _tmp34_ = NULL;
	GtkScale* _tmp35_ = NULL;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	parent_class = G_OBJECT_CLASS (elementary_redshift_widgets_information_grid_parent_class);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGrid);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp0_ = _ ("Schedule:");
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp1_ = elementary_redshift_widgets_setting_label_new (_tmp0_);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp1_);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->mode_setting_label);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->mode_setting_label = _tmp1_;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp2_ = elementary_redshift_indicator_settings;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp3_ = elementary_redshift_indicator_settings;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp4_ = elementary_redshift_services_settings_get_schedule_mode (_tmp3_);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp5_ = _tmp4_;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp6_ = elementary_redshift_services_settings_get_mode_name (_tmp2_, _tmp5_);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp7_ = _tmp6_;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp8_ = (GtkLabel*) gtk_label_new (_tmp7_);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp8_);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->mode_label);
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->mode_label = _tmp8_;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_free0 (_tmp7_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp9_ = self->priv->mode_label;
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp9_, GTK_ALIGN_START);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp10_ = _ ("Temperature:");
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp11_ = elementary_redshift_widgets_setting_label_new (_tmp10_);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp11_);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_setting_label);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->temperature_setting_label = _tmp11_;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp12_ = _ ("Unknown");
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp13_ = (GtkLabel*) gtk_label_new (_tmp12_);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp13_);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_label);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->temperature_label = _tmp13_;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp14_ = self->priv->temperature_label;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp14_, GTK_ALIGN_START);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp15_ = _ ("Period:");
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp16_ = elementary_redshift_widgets_setting_label_new (_tmp15_);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp16_);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->period_setting_label);
#line 51 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->period_setting_label = _tmp16_;
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp17_ = _ ("Unknown");
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp18_ = (GtkLabel*) gtk_label_new (_tmp17_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp18_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->period_label);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->period_label = _tmp18_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp19_ = self->priv->period_label;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp19_, GTK_ALIGN_START);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp20_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_HORIZONTAL, (gdouble) 30, (gdouble) 70, (gdouble) 1);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_object_ref_sink (_tmp20_);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_scale);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv->temperature_scale = _tmp20_;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp21_ = self->priv->temperature_scale;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp22_ = gtk_range_get_adjustment ((GtkRange*) _tmp21_);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp23_ = _tmp22_;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp24_ = elementary_redshift_indicator_settings;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp25_ = elementary_redshift_services_settings_get_temperature (_tmp24_);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp26_ = _tmp25_;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_adjustment_set_value (_tmp23_, (gdouble) (_tmp26_ / 100));
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp27_ = self->priv->temperature_scale;
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_scale_set_value_pos (_tmp27_, GTK_POS_TOP);
#line 58 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp28_ = self->priv->temperature_scale;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_signal_connect_object (_tmp28_, "format-value", (GCallback) __elementary_redshift_widgets_information_grid___lambda5__gtk_scale_format_value, self, 0);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp29_ = self->priv->mode_setting_label;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp29_, 0, 0, 1, 1);
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp30_ = self->priv->mode_label;
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp30_, 1, 0, 1, 1);
#line 64 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp31_ = self->priv->temperature_setting_label;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp31_, 0, 1, 1, 1);
#line 65 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp32_ = self->priv->temperature_label;
#line 65 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp32_, 1, 1, 1, 1);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp33_ = self->priv->period_setting_label;
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp33_, 0, 2, 1, 1);
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp34_ = self->priv->period_label;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp34_, 1, 2, 1, 1);
#line 68 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_tmp35_ = self->priv->temperature_scale;
#line 68 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp35_, 0, 3, 2, 1);
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	elementary_redshift_widgets_information_grid_connect_signals (self);
#line 72 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	elementary_redshift_widgets_information_grid_update (self);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	return obj;
#line 560 "InformationGrid.c"
}


static void elementary_redshift_widgets_information_grid_class_init (ElementaryRedshiftWidgetsInformationGridClass * klass) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	elementary_redshift_widgets_information_grid_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftWidgetsInformationGridPrivate));
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	G_OBJECT_CLASS (klass)->constructor = elementary_redshift_widgets_information_grid_constructor;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_widgets_information_grid_finalize;
#line 573 "InformationGrid.c"
}


static void elementary_redshift_widgets_information_grid_instance_init (ElementaryRedshiftWidgetsInformationGrid * self) {
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self->priv = ELEMENTARY_REDSHIFT_WIDGETS_INFORMATION_GRID_GET_PRIVATE (self);
#line 580 "InformationGrid.c"
}


static void elementary_redshift_widgets_information_grid_finalize (GObject* obj) {
	ElementaryRedshiftWidgetsInformationGrid * self;
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_INFORMATION_GRID, ElementaryRedshiftWidgetsInformationGrid);
#line 25 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->mode_setting_label);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_setting_label);
#line 28 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->period_setting_label);
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->mode_label);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_label);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->period_label);
#line 33 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	_g_object_unref0 (self->priv->temperature_scale);
#line 23 "/home/samthomas/Development/elementary-redshift/src/Widgets/InformationGrid.vala"
	G_OBJECT_CLASS (elementary_redshift_widgets_information_grid_parent_class)->finalize (obj);
#line 604 "InformationGrid.c"
}


GType elementary_redshift_widgets_information_grid_get_type (void) {
	static volatile gsize elementary_redshift_widgets_information_grid_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_widgets_information_grid_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftWidgetsInformationGridClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_widgets_information_grid_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftWidgetsInformationGrid), 0, (GInstanceInitFunc) elementary_redshift_widgets_information_grid_instance_init, NULL };
		GType elementary_redshift_widgets_information_grid_type_id;
		elementary_redshift_widgets_information_grid_type_id = g_type_register_static (gtk_grid_get_type (), "ElementaryRedshiftWidgetsInformationGrid", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_widgets_information_grid_type_id__volatile, elementary_redshift_widgets_information_grid_type_id);
	}
	return elementary_redshift_widgets_information_grid_type_id__volatile;
}



