/* Schedule.c generated by valac 0.34.5, the Vala compiler
 * generated from Schedule.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>


#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE (elementary_redshift_widgets_schedule_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsSchedule))
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsScheduleClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SCHEDULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SCHEDULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE))
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsScheduleClass))

typedef struct _ElementaryRedshiftWidgetsSchedule ElementaryRedshiftWidgetsSchedule;
typedef struct _ElementaryRedshiftWidgetsScheduleClass ElementaryRedshiftWidgetsScheduleClass;
typedef struct _ElementaryRedshiftWidgetsSchedulePrivate ElementaryRedshiftWidgetsSchedulePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL (elementary_redshift_widgets_setting_label_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))

typedef struct _ElementaryRedshiftWidgetsSettingLabel ElementaryRedshiftWidgetsSettingLabel;
typedef struct _ElementaryRedshiftWidgetsSettingLabelClass ElementaryRedshiftWidgetsSettingLabelClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ElementaryRedshiftWidgetsSchedule {
	GtkGrid parent_instance;
	ElementaryRedshiftWidgetsSchedulePrivate * priv;
};

struct _ElementaryRedshiftWidgetsScheduleClass {
	GtkGridClass parent_class;
};

struct _ElementaryRedshiftWidgetsSchedulePrivate {
	GtkStackSwitcher* mode;
	GtkStack* stack;
	GraniteWidgetsTimePicker* daytime;
	GraniteWidgetsTimePicker* nighttime;
};


static gpointer elementary_redshift_widgets_schedule_parent_class = NULL;
extern ElementaryRedshiftServicesSettings* elementary_redshift_plug_settings;
extern GtkSizeGroup* elementary_redshift_plug_start_size_group;
extern GtkSizeGroup* elementary_redshift_plug_end_size_group;

GType elementary_redshift_widgets_schedule_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsSchedulePrivate))
enum  {
	ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_DUMMY_PROPERTY
};
ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_new (void);
ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_construct (GType object_type);
static void elementary_redshift_widgets_schedule_connect_signals (ElementaryRedshiftWidgetsSchedule* self);
static void __lambda4_ (ElementaryRedshiftWidgetsSchedule* self);
GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
void elementary_redshift_services_settings_set_schedule_mode (ElementaryRedshiftServicesSettings* self, const gchar* value);
static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda5_ (ElementaryRedshiftWidgetsSchedule* self);
void elementary_redshift_services_settings_set_day (ElementaryRedshiftServicesSettings* self, GDateTime* d);
static void ___lambda5__granite_widgets_time_picker_time_changed (GraniteWidgetsTimePicker* _sender, gpointer self);
static void __lambda6_ (ElementaryRedshiftWidgetsSchedule* self);
void elementary_redshift_services_settings_set_night (ElementaryRedshiftServicesSettings* self, GDateTime* d);
static void ___lambda6__granite_widgets_time_picker_time_changed (GraniteWidgetsTimePicker* _sender, gpointer self);
static void __lambda7_ (ElementaryRedshiftWidgetsSchedule* self);
static void elementary_redshift_widgets_schedule_update (ElementaryRedshiftWidgetsSchedule* self);
static void ___lambda7__granite_services_settings_changed (GraniteServicesSettings* _sender, gpointer self);
const gchar* elementary_redshift_services_settings_get_schedule_mode (ElementaryRedshiftServicesSettings* self);
GDateTime* elementary_redshift_services_settings_get_day (ElementaryRedshiftServicesSettings* self);
GDateTime* elementary_redshift_services_settings_get_night (ElementaryRedshiftServicesSettings* self);
static GObject * elementary_redshift_widgets_schedule_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label);
GType elementary_redshift_widgets_setting_label_get_type (void) G_GNUC_CONST;
gchar* elementary_redshift_services_settings_get_mode_name (ElementaryRedshiftServicesSettings* self, const gchar* mode);
static void elementary_redshift_widgets_schedule_finalize (GObject* obj);


ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_construct (GType object_type) {
	ElementaryRedshiftWidgetsSchedule * self = NULL;
#line 33 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self = (ElementaryRedshiftWidgetsSchedule*) g_object_new (object_type, "margin", 12, "column-spacing", 12, "halign", GTK_ALIGN_CENTER, NULL);
#line 32 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	return self;
#line 131 "Schedule.c"
}


ElementaryRedshiftWidgetsSchedule* elementary_redshift_widgets_schedule_new (void) {
#line 32 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	return elementary_redshift_widgets_schedule_construct (ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE);
#line 138 "Schedule.c"
}


static void __lambda4_ (ElementaryRedshiftWidgetsSchedule* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkStack* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
#line 100 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 100 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = self->priv->stack;
#line 100 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = gtk_stack_get_visible_child_name (_tmp1_);
#line 100 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = _tmp2_;
#line 100 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_services_settings_set_schedule_mode (_tmp0_, _tmp3_);
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp4_ = self->priv->stack;
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp5_ = gtk_stack_get_visible_child_name (_tmp4_);
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp6_ = _tmp5_;
#line 101 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_message ("Schedule.vala:101: %s", _tmp6_);
#line 168 "Schedule.c"
}


static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 99 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	__lambda4_ ((ElementaryRedshiftWidgetsSchedule*) self);
#line 175 "Schedule.c"
}


static void __lambda5_ (ElementaryRedshiftWidgetsSchedule* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GraniteWidgetsTimePicker* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = self->priv->daytime;
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = granite_widgets_time_picker_get_time (_tmp1_);
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = _tmp2_;
#line 105 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_services_settings_set_day (_tmp0_, _tmp3_);
#line 194 "Schedule.c"
}


static void ___lambda5__granite_widgets_time_picker_time_changed (GraniteWidgetsTimePicker* _sender, gpointer self) {
#line 104 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	__lambda5_ ((ElementaryRedshiftWidgetsSchedule*) self);
#line 201 "Schedule.c"
}


static void __lambda6_ (ElementaryRedshiftWidgetsSchedule* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GraniteWidgetsTimePicker* _tmp1_ = NULL;
	GDateTime* _tmp2_ = NULL;
	GDateTime* _tmp3_ = NULL;
#line 109 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 109 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = self->priv->nighttime;
#line 109 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = granite_widgets_time_picker_get_time (_tmp1_);
#line 109 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = _tmp2_;
#line 109 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_services_settings_set_night (_tmp0_, _tmp3_);
#line 220 "Schedule.c"
}


static void ___lambda6__granite_widgets_time_picker_time_changed (GraniteWidgetsTimePicker* _sender, gpointer self) {
#line 108 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	__lambda6_ ((ElementaryRedshiftWidgetsSchedule*) self);
#line 227 "Schedule.c"
}


static void __lambda7_ (ElementaryRedshiftWidgetsSchedule* self) {
#line 113 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_widgets_schedule_update (self);
#line 234 "Schedule.c"
}


static void ___lambda7__granite_services_settings_changed (GraniteServicesSettings* _sender, gpointer self) {
#line 112 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	__lambda7_ ((ElementaryRedshiftWidgetsSchedule*) self);
#line 241 "Schedule.c"
}


static void elementary_redshift_widgets_schedule_connect_signals (ElementaryRedshiftWidgetsSchedule* self) {
	GtkStack* _tmp0_ = NULL;
	GraniteWidgetsTimePicker* _tmp1_ = NULL;
	GraniteWidgetsTimePicker* _tmp2_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp3_ = NULL;
#line 98 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_return_if_fail (self != NULL);
#line 99 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = self->priv->stack;
#line 99 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_signal_connect_object ((GObject*) _tmp0_, "notify::visible-child", (GCallback) ___lambda4__g_object_notify, self, 0);
#line 104 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = self->priv->daytime;
#line 104 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_signal_connect_object (_tmp1_, "time-changed", (GCallback) ___lambda5__granite_widgets_time_picker_time_changed, self, 0);
#line 108 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = self->priv->nighttime;
#line 108 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_signal_connect_object (_tmp2_, "time-changed", (GCallback) ___lambda6__granite_widgets_time_picker_time_changed, self, 0);
#line 112 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = elementary_redshift_plug_settings;
#line 112 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_signal_connect_object ((GraniteServicesSettings*) _tmp3_, "changed", (GCallback) ___lambda7__granite_services_settings_changed, self, 0);
#line 268 "Schedule.c"
}


static void elementary_redshift_widgets_schedule_update (ElementaryRedshiftWidgetsSchedule* self) {
	GtkStack* _tmp0_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GraniteWidgetsTimePicker* _tmp4_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp5_ = NULL;
	GDateTime* _tmp6_ = NULL;
	GDateTime* _tmp7_ = NULL;
	GraniteWidgetsTimePicker* _tmp8_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp9_ = NULL;
	GDateTime* _tmp10_ = NULL;
	GDateTime* _tmp11_ = NULL;
#line 117 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_return_if_fail (self != NULL);
#line 118 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = self->priv->stack;
#line 118 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = elementary_redshift_plug_settings;
#line 118 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = elementary_redshift_services_settings_get_schedule_mode (_tmp1_);
#line 118 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = _tmp2_;
#line 118 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_set_visible_child_name (_tmp0_, _tmp3_);
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp4_ = self->priv->daytime;
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp5_ = elementary_redshift_plug_settings;
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp6_ = elementary_redshift_services_settings_get_day (_tmp5_);
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp7_ = _tmp6_;
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	granite_widgets_time_picker_set_time (_tmp4_, _tmp7_);
#line 120 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_date_time_unref0 (_tmp7_);
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp8_ = self->priv->nighttime;
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp9_ = elementary_redshift_plug_settings;
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp10_ = elementary_redshift_services_settings_get_night (_tmp9_);
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp11_ = _tmp10_;
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	granite_widgets_time_picker_set_time (_tmp8_, _tmp11_);
#line 121 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_date_time_unref0 (_tmp11_);
#line 321 "Schedule.c"
}


static GObject * elementary_redshift_widgets_schedule_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ElementaryRedshiftWidgetsSchedule * self;
	GtkLabel* schedule_label = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_ = NULL;
	GtkSizeGroup* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	GtkLabel* mode_none_label = NULL;
	const gchar* _tmp8_ = NULL;
	GtkLabel* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	GtkLabel* mode_auto_label = NULL;
	const gchar* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	GtkLabel* _tmp15_ = NULL;
	GtkLabel* mode_custom_label = NULL;
	const gchar* _tmp16_ = NULL;
	GtkLabel* _tmp17_ = NULL;
	GtkLabel* _tmp18_ = NULL;
	GtkLabel* _tmp19_ = NULL;
	GraniteWidgetsTimePicker* _tmp20_ = NULL;
	GtkSizeGroup* _tmp21_ = NULL;
	GraniteWidgetsTimePicker* _tmp22_ = NULL;
	GraniteWidgetsTimePicker* _tmp23_ = NULL;
	GtkSizeGroup* _tmp24_ = NULL;
	GraniteWidgetsTimePicker* _tmp25_ = NULL;
	GtkGrid* mode_custom_grid = NULL;
	GtkGrid* _tmp26_ = NULL;
	GtkGrid* _tmp27_ = NULL;
	GtkGrid* _tmp28_ = NULL;
	GtkGrid* _tmp29_ = NULL;
	GtkGrid* _tmp30_ = NULL;
	GtkGrid* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp33_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp34_ = NULL;
	GtkGrid* _tmp35_ = NULL;
	GraniteWidgetsTimePicker* _tmp36_ = NULL;
	GtkGrid* _tmp37_ = NULL;
	const gchar* _tmp38_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp39_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp40_ = NULL;
	GtkGrid* _tmp41_ = NULL;
	GraniteWidgetsTimePicker* _tmp42_ = NULL;
	GtkStack* _tmp43_ = NULL;
	GtkStack* _tmp44_ = NULL;
	GtkStack* _tmp45_ = NULL;
	GtkLabel* _tmp46_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gchar* _tmp49_ = NULL;
	GtkStack* _tmp50_ = NULL;
	GtkLabel* _tmp51_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp52_ = NULL;
	gchar* _tmp53_ = NULL;
	gchar* _tmp54_ = NULL;
	GtkStack* _tmp55_ = NULL;
	GtkGrid* _tmp56_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp57_ = NULL;
	gchar* _tmp58_ = NULL;
	gchar* _tmp59_ = NULL;
	GtkStackSwitcher* _tmp60_ = NULL;
	GtkStackSwitcher* _tmp61_ = NULL;
	GtkStackSwitcher* _tmp62_ = NULL;
	GtkStackSwitcher* _tmp63_ = NULL;
	GtkStack* _tmp64_ = NULL;
	GtkLabel* _tmp65_ = NULL;
	GtkStackSwitcher* _tmp66_ = NULL;
	GtkStack* _tmp67_ = NULL;
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	parent_class = G_OBJECT_CLASS (elementary_redshift_widgets_schedule_parent_class);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsSchedule);
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp0_ = _ ("Schedule");
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp1_);
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	schedule_label = _tmp1_;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp2_ = schedule_label;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_label_set_xalign (_tmp2_, (gfloat) 0);
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp3_ = schedule_label;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp4_ = schedule_label;
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 43 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_style_context_add_class (_tmp5_, "h4");
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp6_ = elementary_redshift_plug_start_size_group;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp7_ = schedule_label;
#line 44 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_size_group_add_widget (_tmp6_, (GtkWidget*) _tmp7_);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp8_ = _ ("Don't turn on automatically.");
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp9_ = (GtkLabel*) gtk_label_new (_tmp8_);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp9_);
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	mode_none_label = _tmp9_;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp10_ = mode_none_label;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_set (_tmp10_, "wrap", TRUE, NULL);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp11_ = mode_none_label;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_label_set_justify (_tmp11_, GTK_JUSTIFY_CENTER);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp12_ = _ ("Automatically use location to adjust the\n" \
"screen temperature based on the time of day.");
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp13_ = (GtkLabel*) gtk_label_new (_tmp12_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp13_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	mode_auto_label = _tmp13_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp14_ = mode_auto_label;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_set (_tmp14_, "wrap", TRUE, NULL);
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp15_ = mode_auto_label;
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_label_set_justify (_tmp15_, GTK_JUSTIFY_CENTER);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp16_ = _ ("Use custom schedule.");
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp17_ = (GtkLabel*) gtk_label_new (_tmp16_);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp17_);
#line 57 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	mode_custom_label = _tmp17_;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp18_ = mode_custom_label;
#line 58 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_set (_tmp18_, "wrap", TRUE, NULL);
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp19_ = mode_custom_label;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_label_set_justify (_tmp19_, GTK_JUSTIFY_CENTER);
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp20_ = granite_widgets_time_picker_new ();
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp20_);
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->daytime);
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self->priv->daytime = _tmp20_;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp21_ = elementary_redshift_plug_end_size_group;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp22_ = self->priv->daytime;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_size_group_add_widget (_tmp21_, (GtkWidget*) _tmp22_);
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp23_ = granite_widgets_time_picker_new ();
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp23_);
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->nighttime);
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self->priv->nighttime = _tmp23_;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp24_ = elementary_redshift_plug_end_size_group;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp25_ = self->priv->nighttime;
#line 64 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_size_group_add_widget (_tmp24_, (GtkWidget*) _tmp25_);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp26_ = (GtkGrid*) gtk_grid_new ();
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp26_);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	mode_custom_grid = _tmp26_;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp27_ = mode_custom_grid;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_set ((GtkWidget*) _tmp27_, "margin", 12, NULL);
#line 68 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp28_ = mode_custom_grid;
#line 68 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_set_row_spacing (_tmp28_, 12);
#line 69 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp29_ = mode_custom_grid;
#line 69 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_set_column_spacing (_tmp29_, 12);
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp30_ = mode_custom_grid;
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp30_, GTK_ALIGN_CENTER);
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp31_ = mode_custom_grid;
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp32_ = _ ("Day starts:");
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp33_ = elementary_redshift_widgets_setting_label_new (_tmp32_);
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp33_);
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp34_ = _tmp33_;
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach (_tmp31_, (GtkWidget*) _tmp34_, 0, 0, 1, 1);
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (_tmp34_);
#line 72 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp35_ = mode_custom_grid;
#line 72 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp36_ = self->priv->daytime;
#line 72 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach (_tmp35_, (GtkWidget*) _tmp36_, 1, 0, 1, 1);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp37_ = mode_custom_grid;
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp38_ = _ ("Night starts:");
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp39_ = elementary_redshift_widgets_setting_label_new (_tmp38_);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp39_);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp40_ = _tmp39_;
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach (_tmp37_, (GtkWidget*) _tmp40_, 0, 1, 1, 1);
#line 73 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (_tmp40_);
#line 74 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp41_ = mode_custom_grid;
#line 74 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp42_ = self->priv->nighttime;
#line 74 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach (_tmp41_, (GtkWidget*) _tmp42_, 1, 1, 1, 1);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp43_ = (GtkStack*) gtk_stack_new ();
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp43_);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->stack);
#line 76 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self->priv->stack = _tmp43_;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp44_ = self->priv->stack;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_set_transition_type (_tmp44_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp45_ = self->priv->stack;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp46_ = mode_none_label;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp47_ = elementary_redshift_plug_settings;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp48_ = elementary_redshift_services_settings_get_mode_name (_tmp47_, "none");
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp49_ = _tmp48_;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_add_titled (_tmp45_, (GtkWidget*) _tmp46_, "none", _tmp49_);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_free0 (_tmp49_);
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp50_ = self->priv->stack;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp51_ = mode_auto_label;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp52_ = elementary_redshift_plug_settings;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp53_ = elementary_redshift_services_settings_get_mode_name (_tmp52_, "auto");
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp54_ = _tmp53_;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_add_titled (_tmp50_, (GtkWidget*) _tmp51_, "auto", _tmp54_);
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_free0 (_tmp54_);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp55_ = self->priv->stack;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp56_ = mode_custom_grid;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp57_ = elementary_redshift_plug_settings;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp58_ = elementary_redshift_services_settings_get_mode_name (_tmp57_, "custom");
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp59_ = _tmp58_;
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_add_titled (_tmp55_, (GtkWidget*) _tmp56_, "custom", _tmp59_);
#line 80 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_free0 (_tmp59_);
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp60_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_object_ref_sink (_tmp60_);
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->mode);
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self->priv->mode = _tmp60_;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp61_ = self->priv->mode;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_widget_set_margin_top ((GtkWidget*) _tmp61_, 12);
#line 84 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp62_ = self->priv->mode;
#line 84 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp62_, GTK_ALIGN_CENTER);
#line 85 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp63_ = self->priv->mode;
#line 85 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp64_ = self->priv->stack;
#line 85 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_stack_switcher_set_stack (_tmp63_, _tmp64_);
#line 88 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp65_ = schedule_label;
#line 88 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp65_, 0, 0, 1, 1);
#line 89 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp66_ = self->priv->mode;
#line 89 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp66_, 0, 1, 1, 1);
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_tmp67_ = self->priv->stack;
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp67_, 0, 2, 1, 1);
#line 92 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 94 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_widgets_schedule_connect_signals (self);
#line 95 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_widgets_schedule_update (self);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (mode_custom_grid);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (mode_custom_label);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (mode_auto_label);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (mode_none_label);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (schedule_label);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	return obj;
#line 680 "Schedule.c"
}


static void elementary_redshift_widgets_schedule_class_init (ElementaryRedshiftWidgetsScheduleClass * klass) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	elementary_redshift_widgets_schedule_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftWidgetsSchedulePrivate));
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	G_OBJECT_CLASS (klass)->constructor = elementary_redshift_widgets_schedule_constructor;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_widgets_schedule_finalize;
#line 693 "Schedule.c"
}


static void elementary_redshift_widgets_schedule_instance_init (ElementaryRedshiftWidgetsSchedule * self) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self->priv = ELEMENTARY_REDSHIFT_WIDGETS_SCHEDULE_GET_PRIVATE (self);
#line 700 "Schedule.c"
}


static void elementary_redshift_widgets_schedule_finalize (GObject* obj) {
	ElementaryRedshiftWidgetsSchedule * self;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SCHEDULE, ElementaryRedshiftWidgetsSchedule);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->mode);
#line 27 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->stack);
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->daytime);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	_g_object_unref0 (self->priv->nighttime);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Schedule.vala"
	G_OBJECT_CLASS (elementary_redshift_widgets_schedule_parent_class)->finalize (obj);
#line 718 "Schedule.c"
}


GType elementary_redshift_widgets_schedule_get_type (void) {
	static volatile gsize elementary_redshift_widgets_schedule_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_widgets_schedule_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftWidgetsScheduleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_widgets_schedule_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftWidgetsSchedule), 0, (GInstanceInitFunc) elementary_redshift_widgets_schedule_instance_init, NULL };
		GType elementary_redshift_widgets_schedule_type_id;
		elementary_redshift_widgets_schedule_type_id = g_type_register_static (gtk_grid_get_type (), "ElementaryRedshiftWidgetsSchedule", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_widgets_schedule_type_id__volatile, elementary_redshift_widgets_schedule_type_id);
	}
	return elementary_redshift_widgets_schedule_type_id__volatile;
}



