/* SettingLabel.c generated by valac 0.34.5, the Vala compiler
 * generated from SettingLabel.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL (elementary_redshift_widgets_setting_label_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))

typedef struct _ElementaryRedshiftWidgetsSettingLabel ElementaryRedshiftWidgetsSettingLabel;
typedef struct _ElementaryRedshiftWidgetsSettingLabelClass ElementaryRedshiftWidgetsSettingLabelClass;
typedef struct _ElementaryRedshiftWidgetsSettingLabelPrivate ElementaryRedshiftWidgetsSettingLabelPrivate;

struct _ElementaryRedshiftWidgetsSettingLabel {
	GtkLabel parent_instance;
	ElementaryRedshiftWidgetsSettingLabelPrivate * priv;
};

struct _ElementaryRedshiftWidgetsSettingLabelClass {
	GtkLabelClass parent_class;
};


static gpointer elementary_redshift_widgets_setting_label_parent_class = NULL;

GType elementary_redshift_widgets_setting_label_get_type (void) G_GNUC_CONST;
enum  {
	ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_DUMMY_PROPERTY
};
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label);
static GObject * elementary_redshift_widgets_setting_label_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);


ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label) {
	ElementaryRedshiftWidgetsSettingLabel * self = NULL;
	const gchar* _tmp0_ = NULL;
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	g_return_val_if_fail (label != NULL, NULL);
#line 27 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	_tmp0_ = label;
#line 27 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	self = (ElementaryRedshiftWidgetsSettingLabel*) g_object_new (object_type, "label", _tmp0_, NULL);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	return self;
#line 76 "SettingLabel.c"
}


ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label) {
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	return elementary_redshift_widgets_setting_label_construct (ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, label);
#line 83 "SettingLabel.c"
}


static GObject * elementary_redshift_widgets_setting_label_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ElementaryRedshiftWidgetsSettingLabel * self;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	parent_class = G_OBJECT_CLASS (elementary_redshift_widgets_setting_label_parent_class);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel);
#line 31 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_END);
#line 32 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	gtk_widget_set_margin_start ((GtkWidget*) self, 12);
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	return obj;
#line 103 "SettingLabel.c"
}


static void elementary_redshift_widgets_setting_label_class_init (ElementaryRedshiftWidgetsSettingLabelClass * klass) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	elementary_redshift_widgets_setting_label_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/SettingLabel.vala"
	G_OBJECT_CLASS (klass)->constructor = elementary_redshift_widgets_setting_label_constructor;
#line 112 "SettingLabel.c"
}


static void elementary_redshift_widgets_setting_label_instance_init (ElementaryRedshiftWidgetsSettingLabel * self) {
}


GType elementary_redshift_widgets_setting_label_get_type (void) {
	static volatile gsize elementary_redshift_widgets_setting_label_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_widgets_setting_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftWidgetsSettingLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_widgets_setting_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftWidgetsSettingLabel), 0, (GInstanceInitFunc) elementary_redshift_widgets_setting_label_instance_init, NULL };
		GType elementary_redshift_widgets_setting_label_type_id;
		elementary_redshift_widgets_setting_label_type_id = g_type_register_static (gtk_label_get_type (), "ElementaryRedshiftWidgetsSettingLabel", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_widgets_setting_label_type_id__volatile, elementary_redshift_widgets_setting_label_type_id);
	}
	return elementary_redshift_widgets_setting_label_type_id__volatile;
}



