/* Temperature.c generated by valac 0.34.5, the Vala compiler
 * generated from Temperature.vala, do not modify */

/*-
 * Copyright (c) 2016 Sam Thomas (https://github.com/sgpthomas/elementary-redshift)
 *
 * This is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * Authored by: Sam Thomas <sgpthomas@gmail.com>
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <granite.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE (elementary_redshift_widgets_temperature_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperature))
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperatureClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_TEMPERATURE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_TEMPERATURE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE))
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperatureClass))

typedef struct _ElementaryRedshiftWidgetsTemperature ElementaryRedshiftWidgetsTemperature;
typedef struct _ElementaryRedshiftWidgetsTemperatureClass ElementaryRedshiftWidgetsTemperatureClass;
typedef struct _ElementaryRedshiftWidgetsTemperaturePrivate ElementaryRedshiftWidgetsTemperaturePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS (elementary_redshift_services_settings_get_type ())
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettings))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS))
#define ELEMENTARY_REDSHIFT_SERVICES_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_SERVICES_TYPE_SETTINGS, ElementaryRedshiftServicesSettingsClass))

typedef struct _ElementaryRedshiftServicesSettings ElementaryRedshiftServicesSettings;
typedef struct _ElementaryRedshiftServicesSettingsClass ElementaryRedshiftServicesSettingsClass;

#define ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL (elementary_redshift_widgets_setting_label_get_type ())
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabel))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_IS_SETTING_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL))
#define ELEMENTARY_REDSHIFT_WIDGETS_SETTING_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_SETTING_LABEL, ElementaryRedshiftWidgetsSettingLabelClass))

typedef struct _ElementaryRedshiftWidgetsSettingLabel ElementaryRedshiftWidgetsSettingLabel;
typedef struct _ElementaryRedshiftWidgetsSettingLabelClass ElementaryRedshiftWidgetsSettingLabelClass;

struct _ElementaryRedshiftWidgetsTemperature {
	GtkGrid parent_instance;
	ElementaryRedshiftWidgetsTemperaturePrivate * priv;
};

struct _ElementaryRedshiftWidgetsTemperatureClass {
	GtkGridClass parent_class;
};

struct _ElementaryRedshiftWidgetsTemperaturePrivate {
	GtkScale* day_temp_scale;
	GtkScale* night_temp_scale;
};


static gpointer elementary_redshift_widgets_temperature_parent_class = NULL;
extern ElementaryRedshiftServicesSettings* elementary_redshift_plug_settings;
extern GtkSizeGroup* elementary_redshift_plug_start_size_group;
extern GtkSizeGroup* elementary_redshift_plug_end_size_group;

GType elementary_redshift_widgets_temperature_get_type (void) G_GNUC_CONST;
#define ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperaturePrivate))
enum  {
	ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_DUMMY_PROPERTY
};
ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_new (void);
ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_construct (GType object_type);
static void elementary_redshift_widgets_temperature_connect_signals (ElementaryRedshiftWidgetsTemperature* self);
static void __lambda8_ (ElementaryRedshiftWidgetsTemperature* self);
GType elementary_redshift_services_settings_get_type (void) G_GNUC_CONST;
void elementary_redshift_services_settings_set_day_temperature (ElementaryRedshiftServicesSettings* self, gint value);
static void ___lambda8__gtk_range_value_changed (GtkRange* _sender, gpointer self);
static void __lambda9_ (ElementaryRedshiftWidgetsTemperature* self);
void elementary_redshift_services_settings_set_night_temperature (ElementaryRedshiftServicesSettings* self, gint value);
static void ___lambda9__gtk_range_value_changed (GtkRange* _sender, gpointer self);
static void __lambda10_ (ElementaryRedshiftWidgetsTemperature* self);
gint elementary_redshift_services_settings_get_day_temperature (ElementaryRedshiftServicesSettings* self);
static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda11_ (ElementaryRedshiftWidgetsTemperature* self);
gint elementary_redshift_services_settings_get_night_temperature (ElementaryRedshiftServicesSettings* self);
static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static GObject * elementary_redshift_widgets_temperature_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_new (const gchar* label);
ElementaryRedshiftWidgetsSettingLabel* elementary_redshift_widgets_setting_label_construct (GType object_type, const gchar* label);
GType elementary_redshift_widgets_setting_label_get_type (void) G_GNUC_CONST;
static gchar* _elementary_redshift_widgets_temperature___lambda12_ (ElementaryRedshiftWidgetsTemperature* self, gdouble val);
static gchar* __elementary_redshift_widgets_temperature___lambda12__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self);
static gchar* _elementary_redshift_widgets_temperature___lambda13_ (ElementaryRedshiftWidgetsTemperature* self, gdouble val);
static gchar* __elementary_redshift_widgets_temperature___lambda13__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self);
static void elementary_redshift_widgets_temperature_finalize (GObject* obj);


ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_construct (GType object_type) {
	ElementaryRedshiftWidgetsTemperature * self = NULL;
#line 30 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self = (ElementaryRedshiftWidgetsTemperature*) g_object_new (object_type, "margin", 12, "row-spacing", 12, "column-spacing", 12, "halign", GTK_ALIGN_CENTER, NULL);
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return self;
#line 127 "Temperature.c"
}


ElementaryRedshiftWidgetsTemperature* elementary_redshift_widgets_temperature_new (void) {
#line 29 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return elementary_redshift_widgets_temperature_construct (ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE);
#line 134 "Temperature.c"
}


static void __lambda8_ (ElementaryRedshiftWidgetsTemperature* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GtkScale* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = self->priv->day_temp_scale;
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = gtk_range_get_value ((GtkRange*) _tmp1_);
#line 79 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	elementary_redshift_services_settings_set_day_temperature (_tmp0_, ((gint) _tmp2_) * 100);
#line 150 "Temperature.c"
}


static void ___lambda8__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	__lambda8_ ((ElementaryRedshiftWidgetsTemperature*) self);
#line 157 "Temperature.c"
}


static void __lambda9_ (ElementaryRedshiftWidgetsTemperature* self) {
	ElementaryRedshiftServicesSettings* _tmp0_ = NULL;
	GtkScale* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = elementary_redshift_plug_settings;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = self->priv->night_temp_scale;
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = gtk_range_get_value ((GtkRange*) _tmp1_);
#line 83 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	elementary_redshift_services_settings_set_night_temperature (_tmp0_, ((gint) _tmp2_) * 100);
#line 173 "Temperature.c"
}


static void ___lambda9__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	__lambda9_ ((ElementaryRedshiftWidgetsTemperature*) self);
#line 180 "Temperature.c"
}


static void __lambda10_ (ElementaryRedshiftWidgetsTemperature* self) {
	GtkScale* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = self->priv->day_temp_scale;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = gtk_range_get_adjustment ((GtkRange*) _tmp0_);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = _tmp1_;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp3_ = elementary_redshift_plug_settings;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp4_ = elementary_redshift_services_settings_get_day_temperature (_tmp3_);
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp5_ = _tmp4_;
#line 87 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_adjustment_set_value (_tmp2_, (gdouble) (_tmp5_ / 100));
#line 205 "Temperature.c"
}


static void ___lambda10__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 86 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	__lambda10_ ((ElementaryRedshiftWidgetsTemperature*) self);
#line 212 "Temperature.c"
}


static void __lambda11_ (ElementaryRedshiftWidgetsTemperature* self) {
	GtkScale* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = self->priv->night_temp_scale;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = gtk_range_get_adjustment ((GtkRange*) _tmp0_);
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = _tmp1_;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp3_ = elementary_redshift_plug_settings;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp4_ = elementary_redshift_services_settings_get_night_temperature (_tmp3_);
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp5_ = _tmp4_;
#line 91 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_adjustment_set_value (_tmp2_, (gdouble) (_tmp5_ / 100));
#line 237 "Temperature.c"
}


static void ___lambda11__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	__lambda11_ ((ElementaryRedshiftWidgetsTemperature*) self);
#line 244 "Temperature.c"
}


static void elementary_redshift_widgets_temperature_connect_signals (ElementaryRedshiftWidgetsTemperature* self) {
	GtkScale* _tmp0_ = NULL;
	GtkScale* _tmp1_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp2_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp3_ = NULL;
#line 77 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = self->priv->day_temp_scale;
#line 78 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object ((GtkRange*) _tmp0_, "value-changed", (GCallback) ___lambda8__gtk_range_value_changed, self, 0);
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = self->priv->night_temp_scale;
#line 82 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object ((GtkRange*) _tmp1_, "value-changed", (GCallback) ___lambda9__gtk_range_value_changed, self, 0);
#line 86 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = elementary_redshift_plug_settings;
#line 86 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object ((GObject*) _tmp2_, "notify::day-temperature", (GCallback) ___lambda10__g_object_notify, self, 0);
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp3_ = elementary_redshift_plug_settings;
#line 90 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object ((GObject*) _tmp3_, "notify::night-temperature", (GCallback) ___lambda11__g_object_notify, self, 0);
#line 271 "Temperature.c"
}


static gchar* _elementary_redshift_widgets_temperature___lambda12_ (ElementaryRedshiftWidgetsTemperature* self, gdouble val) {
	gchar* result = NULL;
	gdouble _tmp0_ = 0.0;
	gchar* _tmp1_ = NULL;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = val;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = g_strdup_printf (" %.f00 K", _tmp0_);
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	result = _tmp1_;
#line 67 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return result;
#line 287 "Temperature.c"
}


static gchar* __elementary_redshift_widgets_temperature___lambda12__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self) {
	gchar* result;
	result = _elementary_redshift_widgets_temperature___lambda12_ ((ElementaryRedshiftWidgetsTemperature*) self, value);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return result;
#line 296 "Temperature.c"
}


static gchar* _elementary_redshift_widgets_temperature___lambda13_ (ElementaryRedshiftWidgetsTemperature* self, gdouble val) {
	gchar* result = NULL;
	gdouble _tmp0_ = 0.0;
	gchar* _tmp1_ = NULL;
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = val;
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = g_strdup_printf (" %.f00 K", _tmp0_);
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	result = _tmp1_;
#line 71 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return result;
#line 312 "Temperature.c"
}


static gchar* __elementary_redshift_widgets_temperature___lambda13__gtk_scale_format_value (GtkScale* _sender, gdouble value, gpointer self) {
	gchar* result;
	result = _elementary_redshift_widgets_temperature___lambda13_ ((ElementaryRedshiftWidgetsTemperature*) self, value);
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return result;
#line 321 "Temperature.c"
}


static GObject * elementary_redshift_widgets_temperature_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ElementaryRedshiftWidgetsTemperature * self;
	GtkLabel* temperature_label = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_ = NULL;
	GtkSizeGroup* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	GtkScale* _tmp8_ = NULL;
	GtkScale* _tmp9_ = NULL;
	GtkAdjustment* _tmp10_ = NULL;
	GtkAdjustment* _tmp11_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	GtkScale* _tmp15_ = NULL;
	GtkScale* _tmp16_ = NULL;
	GtkSizeGroup* _tmp17_ = NULL;
	GtkScale* _tmp18_ = NULL;
	GtkScale* _tmp19_ = NULL;
	GtkScale* _tmp20_ = NULL;
	GtkAdjustment* _tmp21_ = NULL;
	GtkAdjustment* _tmp22_ = NULL;
	ElementaryRedshiftServicesSettings* _tmp23_ = NULL;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
	GtkScale* _tmp26_ = NULL;
	GtkScale* _tmp27_ = NULL;
	GtkSizeGroup* _tmp28_ = NULL;
	GtkScale* _tmp29_ = NULL;
	GtkLabel* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp32_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp33_ = NULL;
	GtkScale* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp36_ = NULL;
	ElementaryRedshiftWidgetsSettingLabel* _tmp37_ = NULL;
	GtkScale* _tmp38_ = NULL;
	GtkScale* _tmp39_ = NULL;
	GtkScale* _tmp40_ = NULL;
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	parent_class = G_OBJECT_CLASS (elementary_redshift_widgets_temperature_parent_class);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperature);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp0_ = _ ("Temperature");
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_object_ref_sink (_tmp1_);
#line 38 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	temperature_label = _tmp1_;
#line 39 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp2_ = temperature_label;
#line 39 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_label_set_xalign (_tmp2_, (gfloat) 0);
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp3_ = temperature_label;
#line 40 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _tmp3_, TRUE);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp4_ = temperature_label;
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 41 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_style_context_add_class (_tmp5_, "h4");
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp6_ = elementary_redshift_plug_start_size_group;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp7_ = temperature_label;
#line 42 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_size_group_add_widget (_tmp6_, (GtkWidget*) _tmp7_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp8_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_HORIZONTAL, (gdouble) 30, (gdouble) 70, (gdouble) 1);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_object_ref_sink (_tmp8_);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (self->priv->day_temp_scale);
#line 45 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self->priv->day_temp_scale = _tmp8_;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp9_ = self->priv->day_temp_scale;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp10_ = gtk_range_get_adjustment ((GtkRange*) _tmp9_);
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp11_ = _tmp10_;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp12_ = elementary_redshift_plug_settings;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp13_ = elementary_redshift_services_settings_get_day_temperature (_tmp12_);
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp14_ = _tmp13_;
#line 46 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_adjustment_set_value (_tmp11_, (gdouble) (_tmp14_ / 100));
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp15_ = self->priv->day_temp_scale;
#line 47 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_scale_add_mark (_tmp15_, (gdouble) 65, GTK_POS_BOTTOM, NULL);
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp16_ = self->priv->day_temp_scale;
#line 48 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_scale_set_value_pos (_tmp16_, GTK_POS_RIGHT);
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp17_ = elementary_redshift_plug_end_size_group;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp18_ = self->priv->day_temp_scale;
#line 49 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_size_group_add_widget (_tmp17_, (GtkWidget*) _tmp18_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp19_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_HORIZONTAL, (gdouble) 30, (gdouble) 70, (gdouble) 1);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_object_ref_sink (_tmp19_);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (self->priv->night_temp_scale);
#line 52 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self->priv->night_temp_scale = _tmp19_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp20_ = self->priv->night_temp_scale;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp21_ = gtk_range_get_adjustment ((GtkRange*) _tmp20_);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp22_ = _tmp21_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp23_ = elementary_redshift_plug_settings;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp24_ = elementary_redshift_services_settings_get_night_temperature (_tmp23_);
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp25_ = _tmp24_;
#line 53 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_adjustment_set_value (_tmp22_, (gdouble) (_tmp25_ / 100));
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp26_ = self->priv->night_temp_scale;
#line 54 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_scale_add_mark (_tmp26_, (gdouble) 35, GTK_POS_BOTTOM, NULL);
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp27_ = self->priv->night_temp_scale;
#line 55 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_scale_set_value_pos (_tmp27_, GTK_POS_RIGHT);
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp28_ = elementary_redshift_plug_end_size_group;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp29_ = self->priv->night_temp_scale;
#line 56 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_size_group_add_widget (_tmp28_, (GtkWidget*) _tmp29_);
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp30_ = temperature_label;
#line 59 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp30_, 0, 0, 1, 1);
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp31_ = _ ("Day Temperature:");
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp32_ = elementary_redshift_widgets_setting_label_new (_tmp31_);
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_object_ref_sink (_tmp32_);
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp33_ = _tmp32_;
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp33_, 0, 1, 1, 1);
#line 60 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (_tmp33_);
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp34_ = self->priv->day_temp_scale;
#line 61 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp34_, 1, 1, 1, 1);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp35_ = _ ("Night Temperature:");
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp36_ = elementary_redshift_widgets_setting_label_new (_tmp35_);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_object_ref_sink (_tmp36_);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp37_ = _tmp36_;
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp37_, 0, 2, 1, 1);
#line 62 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (_tmp37_);
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp38_ = self->priv->night_temp_scale;
#line 63 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp38_, 1, 2, 1, 1);
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp39_ = self->priv->day_temp_scale;
#line 66 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object (_tmp39_, "format-value", (GCallback) __elementary_redshift_widgets_temperature___lambda12__gtk_scale_format_value, self, 0);
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_tmp40_ = self->priv->night_temp_scale;
#line 70 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_signal_connect_object (_tmp40_, "format-value", (GCallback) __elementary_redshift_widgets_temperature___lambda13__gtk_scale_format_value, self, 0);
#line 74 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	elementary_redshift_widgets_temperature_connect_signals (self);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (temperature_label);
#line 36 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	return obj;
#line 527 "Temperature.c"
}


static void elementary_redshift_widgets_temperature_class_init (ElementaryRedshiftWidgetsTemperatureClass * klass) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	elementary_redshift_widgets_temperature_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	g_type_class_add_private (klass, sizeof (ElementaryRedshiftWidgetsTemperaturePrivate));
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	G_OBJECT_CLASS (klass)->constructor = elementary_redshift_widgets_temperature_constructor;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	G_OBJECT_CLASS (klass)->finalize = elementary_redshift_widgets_temperature_finalize;
#line 540 "Temperature.c"
}


static void elementary_redshift_widgets_temperature_instance_init (ElementaryRedshiftWidgetsTemperature * self) {
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self->priv = ELEMENTARY_REDSHIFT_WIDGETS_TEMPERATURE_GET_PRIVATE (self);
#line 547 "Temperature.c"
}


static void elementary_redshift_widgets_temperature_finalize (GObject* obj) {
	ElementaryRedshiftWidgetsTemperature * self;
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ELEMENTARY_REDSHIFT_WIDGETS_TYPE_TEMPERATURE, ElementaryRedshiftWidgetsTemperature);
#line 26 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (self->priv->day_temp_scale);
#line 27 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	_g_object_unref0 (self->priv->night_temp_scale);
#line 24 "/home/samthomas/Development/elementary-redshift/src/Widgets/Temperature.vala"
	G_OBJECT_CLASS (elementary_redshift_widgets_temperature_parent_class)->finalize (obj);
#line 561 "Temperature.c"
}


GType elementary_redshift_widgets_temperature_get_type (void) {
	static volatile gsize elementary_redshift_widgets_temperature_type_id__volatile = 0;
	if (g_once_init_enter (&elementary_redshift_widgets_temperature_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ElementaryRedshiftWidgetsTemperatureClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) elementary_redshift_widgets_temperature_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ElementaryRedshiftWidgetsTemperature), 0, (GInstanceInitFunc) elementary_redshift_widgets_temperature_instance_init, NULL };
		GType elementary_redshift_widgets_temperature_type_id;
		elementary_redshift_widgets_temperature_type_id = g_type_register_static (gtk_grid_get_type (), "ElementaryRedshiftWidgetsTemperature", &g_define_type_info, 0);
		g_once_init_leave (&elementary_redshift_widgets_temperature_type_id__volatile, elementary_redshift_widgets_temperature_type_id);
	}
	return elementary_redshift_widgets_temperature_type_id__volatile;
}



